### ISSUE TITLE
Is there a way to read a whole project?

### ISSUE THREAD

**Issue by nkakouros** [bash-lsp/bash-language-server#109]
My project is organised into several bash script files. Some of them are the library files that contain function definitions. When I have my editor opened with only a non library file open, "go to declaration" function fails to take me to the library file that contains the function definition. If I open the library file manually, "go to declaration" works (even if I close the library file afterwards).

Is this sth my editor's LSP plugin should solve or is it a limitation of this language server?

**Comment by skovhus** [comment]
Thanks @tterranigma. Can you create a minimal reproducible example?

**Comment by tterranigma** [comment]
```
cd /tmp
git clone https://github.com/tterranigma/bash-headstart
cd bash-headstart
code headstart
```

Go to line 8, right click, go to definition, nothing happens.

Ctrl-O -> `headstart-core.bash`

Go to the `headstart` file, repeat go to definition, it works!

**Comment by simson** [comment]
This feature could be great !

**Comment by skovhus** [comment]
This has been supported for some time now. 

Please reopen if you have comments or suggestions.

**Comment by nkakouros** [comment]
@skovhus How is this supported? Is there some configuration I need to do? In my project, all bash scripts and libraries are in a `src/` folder. There is a top level entry script that I use to expose these scripts as a cli. In neovim, no function definition is found unless I open the file that contains the definition first. The version of bash lsp I am running is 1.14.0.

**Comment by skovhus** [comment]
@nkakouros Thanks. A minimal reproducible example would be great. Maybe the file extensions names are non-standard, hence they are not parsed?

**Comment by nkakouros** [comment]
The example in my second comment still exhibits the issue.

> Maybe the file extensions names are non-standard, hence they are not parsed?

Hm.. My files do not have a `.sh` extension. But they have a shebang:

```
!#/usr/bin/env bash
```

Maybe that's the issue?

**Comment by MartialGeek** [comment]
Hello

```
❯ bash-language-server --version
Version is 2.0.0
```

I have the exact same issue with Neovim v0.6.1 and its native LSP support. I followed the instructions in the `nvim-lspconfig` repository: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#bashls. I did not override the default configuration so I only enabled the server with `require'lspconfig'.bashls.setup{}`.

 I have to manually open a script in my project to be indexed by the server.
Here is an example:

```sh
mkdir test-project && cd test-project
touch lib.sh main.sh
chmod +x main.sh
```

And the content of `lib.sh` and `main.sh`:

```sh
#/bin/bash

test-func() {
    echo "test func"
}
```

```sh
#!/bin/bash

source lib.sh

test-func
```

If I open only main.rs, "go-to-definition" on `test-func` does not work. But it works as soon as I also open lib.rs.
Is the default vim-lspconfig setup incomplete? If you have some insights about that it would be very appreciate.
