### ISSUE TITLE
Unexpected launch of programs

### ISSUE THREAD

**Issue by ChillerDragon** [bash-lsp/bash-language-server#1116]
### Code editor

neovim

### Platform

Unix

### Version

b858fd12edf8042882a0a412521a6f71c414efe1

### What steps will reproduce the bug?

Setup neovim with [kickstart](https://github.com/nvim-lua/kickstart.nvim) and add the following line to the init.lua
```
require('lspconfig').bashls.setup {}
```

### How often does it reproduce? Is there a required condition?

Every time. The condition is assigning a variable value to a program that is in PATH that ignores the --help flag and just launches.

### What is the expected behavior?

Not boot any application when requesting the list of auto completions.

### What do you see instead?

A Qt/SDL application booting when I type in neovim with bash-lsp active.

### Additional information

https://github.com/nvim-lua/kickstart.nvim/issues/727

https://private-user-images.githubusercontent.com/20344300/311201407-03333a4b-e18f-4659-b1e1-7010f24366be.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTA5MjcsIm5iZiI6MTcwOTkxMDYyNywicGF0aCI6Ii8yMDM0NDMwMC8zMTEyMDE0MDctMDMzMzNhNGItZTE4Zi00NjU5LWIxZTEtNzAxMGYyNDM2NmJlLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE1MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1M2UyYTIzODU5OGRmZGQ5OGMyZjAwNzZmMzNiOGZlMzNjZGU2NjNjNDFmNTNjYzJhMDVhNGI3MWVkY2YxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VX1XHh8NNWHZrcnpcmrqCRVMqgSOt6fYieUmYm1hPHk

**Comment by ChillerDragon** [comment]
The problems seems to have been introduced in https://github.com/bash-lsp/bash-language-server/pull/1052

**Comment by Zhniing** [comment]
I have encountered the same problem. Is there any workaround so far?

**Comment by ChillerDragon** [comment]
> I have encountered the same problem. Is there any workaround so far?

I use the following workaround https://github.com/ChillerDragon/bash-language-server/commit/70bb02870b33b6b2e98cb8ac2c16247329c424a0

**Comment by peesock** [comment]
This is a REALLY bad idea. Executing arbitrary code just because it's in $PATH is terrible, especially for shell scripters like me, where I actually have a script called `killer` that when executed with any non-valid argument, like `--help`, it will kill every process on the system.

I don't want to worry about that issue when autocompleting. This needs to be either removed, or sandboxed with a tool like [bubblewrap](https://github.com/containers/bubblewrap) or seccomp, although these depend on a linux platform.

**Comment by ChillerDragon** [comment]
> I don't want to worry about that issue when autocompleting. This needs to be either removed, or sandboxed with a tool like [bubblewrap](https://github.com/containers/bubblewrap) or seccomp, although these depend on a linux platform.

I am not sure if the man page is also problematic ``man -P cat ${word} | col -bx`` but I like the idea of a sandbox just to be sure. Or maybe the man page version could read the man page file on disk directly instead of launching a shell command with user input from the completion.

Is running ``man`` and ``col`` safe on every system? Is providing ``word`` as non quoted, non escaped argument safe with all possible inputs? I assume that all possible values for "word" get interpreted as string when passed as bash argument. But it still looks spooky.

**Comment by damonmccain** [comment]
I have the same issue

**Comment by j4k0xb** [comment]
@skovhus please undo this PR for now until a "proper/safe" way has been found
even typing a simple for loop opens some random GUI (`fogcoord` is the first autocomplete item)
![Peek 2024-05-15 15-38](https://github.com/bash-lsp/bash-language-server/assets/55899582/02c40528-9587-4cd8-89f2-f5653cab0eec)

**Comment by skovhus** [comment]
A fix has been deployed in version 5.3.3. Thanks for the ping @j4k0xb
