### ISSUE TITLE
Bash expression with arithmetic operations causing syntax error in bash-language-server

### ISSUE THREAD

**Issue by eval-exec** [bash-lsp/bash-language-server#1130]
### Code editor

Emacs

### Platform

NixOS

### Version

5.1.2

### What steps will reproduce the bug?

Create a file `test.sh`
write content:
```bash
#!/usr/bin/env bash
a=4
b=6
num=$((($a + $b) / 2))
echo ${num}
```
Then bash-language-server will report:
```
(bash-language-server): 08:14:09.764 WARNING    Error while parsing file:///tmp/bash/test.sh: syntax error
```

### How often does it reproduce? Is there a required condition?

No, its can reproduce 100%.

### What is the expected behavior?

no warning.

### What do you see instead?

I see bash-language-server report an error:

```bash
(bash-language-server): 08:14:09.764 WARNING    Error while parsing file:///tmp/bash/test.sh: syntax error
```

**Comment by skovhus** [comment]
This is related to the treesitter bash grammar, so unfortunately nothing we can do here.
