### ISSUE TITLE
Bash IDE VsCode Extension not being updated

### ISSUE THREAD

**Issue by Jimmyscene** [bash-lsp/bash-language-server#1156]
### Code editor

Vscode

### Platform

n/a

### Version

n/a

### What do you see instead?

The VsCode extension hasn't been updated since 7/15/2023, which is two versions ago. This seems to be due to the Personal Access Token being expired

It would be nice to get that token updated, if possible 

Failure:
https://github.com/bash-lsp/bash-language-server/actions/runs/8844342277/job/24286061098
Extension:
https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode

**Comment by dsent** [comment]
I second this! The "rename symbol" functionality is sorely missing in the marketplace version.

**Comment by skovhus** [comment]
Working on it...

**Comment by Jimmyscene** [comment]
Thanks @skovhus !!
