### ISSUE TITLE
The npm package has not updated

### ISSUE THREAD

**Issue by adoyle-h** [bash-lsp/bash-language-server#1159]
The [changelog](https://github.com/bash-lsp/bash-language-server/blob/main/server/CHANGELOG.md) show the latest version is 5.3.1, but [npm](https://www.npmjs.com/package/bash-language-server) only has 5.2.0.
I want to use the feature "Add support for formatting using shfmt (if installed)" which added in 5.3.0. Could you please make a release?

**Comment by skovhus** [comment]
Should be out now.
