### ISSUE TITLE
What unit does bash-language-server use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [bash-lsp/bash-language-server#116]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by skovhus** [comment]
@Avi-D-coder sorry for not responding faster here. I'm actually unsure what we use. How can I check?

**Comment by Avi-D-coder** [comment]
It will depend on how you generate ranges? Is everything loaded into JS strings or are you doing IO.
