### ISSUE TITLE
bash-language-server in vscode extension is not up to date

### ISSUE THREAD

**Issue by bzy-debug** [bash-lsp/bash-language-server#1176]
### Code editor

visual studio code

### Platform

OS X

### Version

vscode extension v1.41.0

### What steps will reproduce the bug?

```
cat ~/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.41.0/node_modules/bash-language-server/package.json | jq '.version'
```

### What do you see instead?

the bash-language-server in vscode extension should be up to date.

```bash
$ cat ~/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.41.0/node_modules/bash-language-server/package.json | jq '.version'
"5.4.0" # expected output
```

### Additional information

The package.json in vscode-client has out-dated dependency of bash-language-server, this causes the published vscode extension always use the outdated bash-langauge-server

**Comment by chris-reeves** [comment]
This can be closed now that #1178 has been merged in.
