### ISSUE TITLE
- Move from perl 5.10 to 5.14 add

### ISSUE THREAD

**Issue by Bdrake317** [bash-lsp/bash-language-server#1245]
- Move from perl 5.10 to 5.14
- Remove Repository plug-in in favor of GitHubMeta
- Switch EOLTests to Test::EOL and add dependency.

_Originally posted by @mwmiller in https://github.com/duckduckgo/duckduckgo/pull/104_

**Comment by skovhus** [comment]
Seems like you are in the wrong repository.
