### ISSUE TITLE
Failed to parse expression: here document

### ISSUE THREAD

**Issue by mkopec3** [bash-lsp/bash-language-server#126]
Code that triggers the issue:

```
#!/bin/sh

cat <<!HEREDOC!
hello
this
is
smth..
!HEREDOC!
```

Screenshot from VSCode:
![bash_ide_heredoc](https://user-images.githubusercontent.com/25580985/56908743-32732380-6aa7-11e9-857f-6dbd7d4a3225.png)

Identified on:
Bash IDE 1.3.3 + VSCode (Version: 1.33.1)

**Comment by mkopec3** [comment]
Seems that the exclamation mark causes the issue

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

I create an issue: https://github.com/tree-sitter/tree-sitter-bash/issues/58

**Comment by beltaurus** [comment]
I had a similar problem, as I was using this in all my scripts:
```
cat <<!
text...
!
```

Although it worked, I thought I was working on the edge of legality, messing with "history" notations, So when I started using shellcheck, I switched to
```
cat <<Q
text...
Q
```

Note that the tabbed entry for readability is important (might impact how this gets fixed):
```
cat <<-!
<tab>...text...
!
```

**Comment by macduke** [comment]
i have a similar problem... 

```
read -r -d '' some-var << __EOF__ || true
blabla
blabla
__EOF__

```
the parser does not like the underlin (__) at the beginning.

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
