### ISSUE TITLE
Failed to parse expression: multi-line strings with eval string

### ISSUE THREAD

**Issue by 0x5a17ed** [bash-lsp/bash-language-server#129]
The following snippets causes bash-language-server to fail parsing the entire document it seems. Vscode highlights the entire file to have a syntax error.
```bash
main() {
    local foo="asd"`
        `"fgh"
}
```

![Bildschirmfoto von 2019-05-11 10-14-50](https://user-images.githubusercontent.com/36956198/57567184-ad0c3f00-73d5-11e9-9d4e-b98b2221336d.png)

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

I create an issue: tree-sitter/tree-sitter-bash#59

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
