### ISSUE TITLE
failed parse 

### ISSUE THREAD

**Issue by wanghekai** [bash-lsp/bash-language-server#130]
failed parse like this 
exec {fd}<>$fd_nic_pipe

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue. What would you call this `<>` construct?

Can you create an issue over here: https://github.com/tree-sitter/tree-sitter-bash

**Comment by vike2000** [comment]
> What would you call this `<>` construct?

https://www.gnu.org/software/bash/manual/bash.html#Opening-File-Descriptors-for-Reading-and-Writing (section 3.6.10)

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
