### ISSUE TITLE
Failed to parse functions

### ISSUE THREAD

**Issue by heftig** [bash-lsp/bash-language-server#133]
This fails to parse:
```bash
foo() (
  true
)
```

Note that a function's body can be any *Compound Command*, so it's also legal to write:
```bash
bar() [[ -e foo ]]
baz() if [[ $a = $b ]]; then
  echo 1
else
  echo 2
fi
```

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

I create an issue: tree-sitter/tree-sitter-bash#60

**Comment by Ben-Voris** [comment]
This was updated here [ld](https://github.com/maxbrunsfeld) pushed a commit that referenced this issue on May 15, 2020

**Comment by skovhus** [comment]
Yes, the fix was merged and release back in 2020. There still seems to be an issue with compound command – but this should be tracked at the tree-sitter-bash repository.
