### ISSUE TITLE
parse fail with here document with variable

### ISSUE THREAD

**Issue by ARCowie28** [bash-lsp/bash-language-server#136]
Parse fails for entire document when you have a here document inside an `if`, that contains a variable as the first expression.

MWE:
```bash
if true; then
  a_string='some stuff to cat'
  cat <<XXX
${a_string}
XXX
fi
```

Issue does not occur if:
- not inside an `if`
- there is anything except newlines before `${a_string}`, including whitespace

**Comment by skovhus** [comment]
Can you create an issue on the treesitter-bash repository? This is a problem with the grammar it seems.

**Comment by skovhus** [comment]
See https://github.com/tree-sitter/tree-sitter-bash/issues/61
