### ISSUE TITLE
Irritating Issue: Problem Tab shows up at all times while Hovering even when it is minimized

### ISSUE THREAD

**Issue by anishmittal2020** [bash-lsp/bash-language-server#140]
```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-21-generic
```
As shown in the following image I can close the problem tab pane by clicking on the `X` symbol at the end. When the extension is enabled, it opens the pane, whenever I hover on any part of the code, which is a bit annoying as, not all the time we want the pane to be open.

If somebody wants it, they could manually open the pane and hover on the code. 

![image](https://user-images.githubusercontent.com/42092626/62412365-90149000-b601-11e9-987d-1c4006800013.png)

**Comment by skovhus** [comment]
Thanks for reporting this.

**Comment by skovhus** [comment]
@anishmittal2020 is this still the case?

**Comment by anishmittal2020** [comment]
@skovhus  Yes. It is still there. 

![image](https://user-images.githubusercontent.com/42092626/81744715-d9a0de00-94a3-11ea-81b9-8f89d18cc222.png)

Even though I removed the explainshell endpoint in the vscode settings (as shown below), I still get the same error.

![image](https://user-images.githubusercontent.com/42092626/81744757-e7566380-94a3-11ea-9aea-06d6af50b578.png)

For those who are not interested in running explain shell server, it will be good if we have  an option to disable this.

**Comment by skovhus** [comment]
> Even though I removed the explainshell endpoint in the vscode settings (as shown below), I still get the same error.

This is VS Code, right? I assume you reloaded VS Code after changing this?

I'm not convinced this issue is related to explain shell. And you attach more of the output log (maybe all of it)? 

Thanks.

**Comment by skovhus** [comment]
Did reloading solve the issue?

**Comment by anishmittal2020** [comment]
Yes. Thank you. Although I would love to have explainshell server working. Could you please answer one technical question: does it take a lot of resources to run a docker container for explainshell. I was worried that it might slow down my laptop, that's why I was not considering it. Also, is it possible to set the explainshell endpoint to `https://explainshell.com/`

**Comment by skovhus** [comment]
> Does it take a lot of resources to run a docker container for explainshell.

I’m not sure. But please share your findings if you try it out. Would also be great with a dockerfile with explainshell. 

> Also, is it possible to set the explainshell endpoint to https://explainshell.com/

I’m pretty sure it is, but it is security risk as you send your code to a third party site.

**Comment by anishmittal2020** [comment]
```
[Error - 4:35:55 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: 404 - "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
  Code: -32603 
onHover 126:2 word="cat"
Query https://explainshell.com/
```

**Comment by skovhus** [comment]
@anishmittal2020 using explainshell.com is apparently depending on https://github.com/idank/explainshell/pull/125 and not related to this issue.
