### ISSUE TITLE
Failed to parse  $(( 1 < 2 ? 1 : 2 )) 

### ISSUE THREAD

**Issue by bleutner** [bash-lsp/bash-language-server#143]
Not entirely sure whether your bugtracker is the correct one for this issue (happens in eclipse shellwax), so feel free to send me elsewhere, if not.

Failed to parse:

    $(( 1 < 2 ? 1 : 2 ))

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

Can you create an issue over here: https://github.com/tree-sitter/tree-sitter-bash

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
