### ISSUE TITLE
Empty diagnostics with coc.nvim

### ISSUE THREAD

**Issue by esn89** [bash-lsp/bash-language-server#154]
I am using this language server with coc.nvim, it is simply started like:

`bash-language-server start` with that argument.

However, when I open up a file, it shows the highlight where the error is but it does not tell me what is wrong with it:
https://i.imgur.com/CHrhcCm.png

**Comment by artem-nefedov** [comment]
I have the same problem.
My vim is `NVIM v0.5.0-95-g2e14dffbb`

**Comment by skovhus** [comment]
Is this still a problem with the latest `bash-language-server`?

**Comment by esn89** [comment]
Hi, I recently upgraded this to 1.7.0 and I can confirm that this is still a problem.
