### ISSUE TITLE
Failed to parse expression [[ X != @(A|B|C) ]]

### ISSUE THREAD

**Issue by BenFradella** [bash-lsp/bash-language-server#158]
![image](https://user-images.githubusercontent.com/43310279/68702518-95fa0580-054e-11ea-8205-86507540b3cb.png)

Present on version 1.5.6 and 1.6.1. I'm assuming on all other versions as well.

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

Can you create an issue over here? https://github.com/tree-sitter/tree-sitter-bash

**Comment by BenFradella** [comment]
Can do

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
