### ISSUE TITLE
Failed to parse expression ${#}

### ISSUE THREAD

**Issue by Hologos** [bash-lsp/bash-language-server#159]
Hi,

the code snippet below generates _Failed to parse expression_ error.

```bash
if [[ ${#} -eq 0 ]]; then
    :
fi
```

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

Can you create an issue over here: https://github.com/tree-sitter/tree-sitter-bash

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar.
