### ISSUE TITLE
Failed to parse expression $(( ))

### ISSUE THREAD

**Issue by Hologos** [bash-lsp/bash-language-server#160]
Hi,

the code snippets below generates _Failed to parse expression_ errors.

```bash
running_status_current_length=$(( (running_status_current_length + 1) % running_status_max_length ))
```

```bash
local number_of_lines=$(( (1 + 1 + number_of_systems) * number_of_transports ))
```

Attaching screenshot to see what exactly it cannot parse.

![Snímek obrazovky 2019-11-27 v 9 41 57](https://user-images.githubusercontent.com/1620004/69707563-4c86ea00-10fa-11ea-98c9-94ffaf29fcd3.png)
![Snímek obrazovky 2019-11-27 v 9 42 20](https://user-images.githubusercontent.com/1620004/69707566-4e50ad80-10fa-11ea-9d90-ff15d5abb41d.png)

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

Can you create an issue over here: https://github.com/tree-sitter/tree-sitter-bash

**Comment by YHRen** [comment]
![screen_shot_at_2020-08-01T16:50:11-04:00](https://user-images.githubusercontent.com/2334880/89110274-2cd95b80-d417-11ea-9c37-81ec9b97acbc.png)

second this.

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar.
