### ISSUE TITLE
Parser fails on case with fallthrough

### ISSUE THREAD

**Issue by slawekb** [bash-lsp/bash-language-server#176]
Version 1.4.0

Reports "Failed to parse expression" on the `;&` in the following code:

```bash
case $CASE in
  case1)
    CASE1=true
    ;&
  case2)
    CASE2=true
    ;;
esac
```

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue – so related to the library used for parsing.

Can you see if this is already reported upstream and maybe create an issue over there: https://github.com/tree-sitter/tree-sitter-bash[](url)

**Comment by gene-pavlovsky** [comment]
Seems to be fixed in the library:
https://github.com/tree-sitter/tree-sitter-bash/commit/8ece09ca4c0b5e59b124cd19fa92c76b1a9e9dd4

**Comment by skovhus** [comment]
Yes, Thanks. We are just missing a release of the library. :)
