### ISSUE TITLE
Parse Failure on Set Line

### ISSUE THREAD

**Issue by kins-dev** [bash-lsp/bash-language-server#177]
I have:
```bash
#!/bin/bash
set -$-ue
```
Which is giving a parse failure.  If I use:
```bash
#!/bin/bash
set -${-}ue
```
There's no parse failure.

```$-``` is the options for the current shell.  I would expect ```set -$-ue``` to be valid, as bash seems just fine with it.

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue – so related to the library used for parsing.

Can you see if this is already reported upstream and maybe create an issue over there: https://github.com/tree-sitter/tree-sitter-bash[](url)
