### ISSUE TITLE
Cannot complete definition that are possible to jump to. 

### ISSUE THREAD

**Issue by przepompownia** [bash-lsp/bash-language-server#190]
Let the project files be an example. Then:
- open `testing/fixtures/sourcing.sh`
- verify that `testing/fixtures/issue101.sh` was analyzed
- write `add_a_u` somewhere in empty line. I do not see `add_a_user` in suggestions.

After manual completion I was able to jump to definition in `issue101.sh`.

**Comment by przepompownia** [comment]
It looks like collecting symbols from the current file only:

https://github.com/bash-lsp/bash-language-server/blob/master/server/src/server.ts#L219
https://github.com/bash-lsp/bash-language-server/blob/790f5a5203af62755d6cec38ef1620e2b2dc0dcd/server/src/analyser.ts#L247

**Comment by skovhus** [comment]
The problem is that we only search for symbols in the current file (see https://github.com/bash-lsp/bash-language-server/blob/master/server/src/server.ts#L219). We should instead search in all files (and prioritize matches in the current file). 

We should probably turn `findSymbolCompletions` into how `findDefinition` works, but taken a partial word.

Note that jump to definition works (write `add_a_user` and click on it jumps to the correct file).

**Comment by skovhus** [comment]
Concern: will this bloat the suggestions? As we have no knowledge of which bash files are sourced, the feature will potentially suggest a lot of irrelevant symbols.

I have a working implementation that I will wrap up so we can try it out.

**Comment by przepompownia** [comment]
Currently we have available lots of symbols irrelevant to current scope (especially local variables from inside the rest of functions) and unavailable other symbols that would be accessible (variables that are only `declare`d and functions from external scripts). 

While bash-language-server is unable to recognize the current scope, providing only function names from external scripts seems to be an intermediate solution.

**Comment by skovhus** [comment]
>  providing only function names from external scripts seems to be an intermediate solution.

Would we limit it to functions? I’m wondering if variables also would be useful (see the sourcing example with colors). But I need to input here as I’m not usually dealing with multiple connected bash files. 

Wondering if we could do something to understand scope better. We could maybe use the parsing tree. @mads-hartmann?

**Comment by skovhus** [comment]
This was released as version 1.9.0.

@przepompownia I'm looking forward to hearing your feedback. Let me know if you suggest any adjustments.

**Comment by przepompownia** [comment]
It is very helpful, especially with description :) Thanks!

**Comment by skovhus** [comment]
> It is very helpful, especially with description :) Thanks!

Glad to hear. Please do not hesitate to create issues with other suggestions. :)
