### ISSUE TITLE
How to enable workspace symbol list support?

### ISSUE THREAD

**Issue by przepompownia** [bash-lsp/bash-language-server#197]
First I ensured that I use the latest version ` "message": "Initialized server v. 1.11.0 for file:///home/***/.githooks"` ;) The I checked the capability using `CocHasProvider`:
```
echo CocHasProvider('workspaceSymbols')
v:false
CocList symbols
[coc.nvim] Error on "CocList symbols": Workspace symbols provider not found for current document
```
However, trying to execute `call CocRequest('bash','workspace/symbol', {'query': 'single'})` ends with no error but also no results (not as expected):
```
[Trace - 16:47:04] Sending request 'workspace/symbol - (4)'.
Params: {
    "query": "single"
}


[Trace - 16:47:04] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "onWorkspaceSymbol"
}


onWorkspaceSymbol
[Trace - 16:47:04] Received response 'workspace/symbol - (4)' in 3ms.
Result: []
```
(at least one locally defined function was expected). 

Is the request correct? I looked at https://microsoft.github.io/language-server-protocol/specification#workspace_symbol

**Comment by skovhus** [comment]
Can you verify that other symbols doesn’t work either? Maybe paste a small example here of the shell script?

**Comment by skovhus** [comment]
> Is matching to the head of symbol name required by LSP or is it your choice? 

That was just what was picked when implementing. It makes sense that the search is using includes instead of startsWith. I would like to avoid making it configurable and hope that includes works for everyone. It also looks like this is what other LSP servers are doing.

Does https://github.com/mads-hartmann/bash-language-server/pull/198 work for you?

**Comment by przepompownia** [comment]
It works and make searching much more useful (assuming that the server will correctly inform the client about existing this functionality) :+1: 
However I still vote for make it like at the example below (tsserver used with CoC):
![camel](https://user-images.githubusercontent.com/11404453/75915162-4ec5b680-5e56-11ea-9b61-c0fea9342b27.png)

**Comment by skovhus** [comment]
@przepompownia thanks, I'll look into fuzzy searching. 

The provider/discoverability issue: it is called `workspaceSymbolProvider` in capabilities. Maybe you should write `workspaceSymbol` (not plural)?

**Comment by przepompownia** [comment]
```
Error on request (hasProvider): Vim(return):Error invoking 'hasProvider' on channel 3 (coc):                                                                                  
workspaceSymbol not supported.                                                                                                                                                
0     
```

**Comment by skovhus** [comment]
I don't really know anything about `CocHasProvider`... Can you find other places where `CocHasProvider` is called with `workspaceSymbols` or `workspaceSymbol`? 

The capabilities object work in vs code, so I'm wondering if it is something else causing this... 🤔 See https://github.com/mads-hartmann/bash-language-server/blob/master/server/src/server.ts#L86 for the list of capabilities

**Comment by przepompownia** [comment]
From the server side `workspaceSymbolProvider` is reported. 
```
[Trace - 02:44:03] Received response 'initialize - (0)' in 1033ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "completionProvider": {
            "resolveProvider": true
        },
        "hoverProvider": true,
        "documentHighlightProvider": true,
        "definitionProvider": true,
        "documentSymbolProvider": true,
        "workspaceSymbolProvider": true,
        "referencesProvider": true
    }
}
```
Maybe it is client-specific issue and it may take me some time to find it.

**Comment by przepompownia** [comment]
Indeed, there was a CoC bug that has been fixed. Thank you for trying to help.
