### ISSUE TITLE
Inform that a variable is not defined

### ISSUE THREAD

**Issue by mhagnumdw** [bash-lsp/bash-language-server#203]
Is it possible to configure to inform that a variable is referenced but not defined?

And is it possible that the "Go to Definition" option is restricted to the current file only?

Versions:
- vscode 1.42.1 (Windows 10)
- Bash IDE 1.8.0

**Comment by skovhus** [comment]
> Is it possible to configure to inform that a variable is referenced but not defined?

Currently, we don't really have support for this. Would be a neat feature, but I'm not sure tree-sitter-bash can give us the necessary information. @mads-hartmann ideas?

> And is it possible that the "Go to Definition" option is restricted to the current file only?

So do you want to restrict it? Or do you want to know if it only is restricted? It should work across files.

**Comment by mads-hartmann** [comment]
> Is it possible to configure to inform that a variable is referenced but not defined?

This is out of scope for this project, I suggest checking out https://www.shellcheck.net it can detect cases like this and a lot more ☺️
