### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by vegerot** [bash-lsp/bash-language-server#208]
I am using this extension as part of the `coc-sh` plugin for coc.nvim.  When I am doing the file completion, I do not see hidden files and directories suggested.  Is there a way to enable this?

**Comment by skovhus** [comment]
>  When I am doing the file completion, I do not see hidden files and directories suggested. Is there a way to enable this?

I'm wondering if we should parse hidden files.

If you are using vs code, can you try setting `bashIde.globPattern` to `**/{.,}*@(.sh|.inc|.bash|.command)` (`**/*@(.sh|.inc|.bash|.command)` is the default)

**Comment by vegerot** [comment]
I'm using coc.nvim.  But I suppose similar settings should work for coc, since I believe it's a fork of the vscode extension.  

I was thinking about not parsing hidden files by default, but parse hidden files once somebody puts a dot "." at the beginning of a path separator

**Comment by skovhus** [comment]
> But I suppose similar settings should work for coc, since I believe it's a fork of the vscode extension.

You can probably use the environment variable `GLOB_PATTERN`. Let me know if it works for you.
