### ISSUE TITLE
Scope aware symbol completion

### ISSUE THREAD

**Issue by skovhus** [bash-lsp/bash-language-server#220]
Currently, when auto-completing, the LSP shows a lot of irrelevant symbols related to the current scope (especially local variables from other function).

Task: figure out if we can use the tree-sitter AST to improve the symbol completion. 

Also see https://github.com/bash-lsp/bash-language-server/issues/190#issuecomment-614260716

**Comment by skovhus** [comment]
@mads-hartmann thoughts?

**Comment by mads-hartmann** [comment]
@skovhus Ideally we'd only show completions for the symbols that are in scope (locally defined in a function, loaded from another file through a `source` invocation, etc.). Doing that correctly would require some pretty sophisticated analysis of the source code though.

So perhaps a smaller first step would be to make it user-configurable what we use to populate the list of completions (local file, workspace, binaries on your path, etc.) :)

**Comment by mads-hartmann** [comment]
If you want to solve completion based on scope then I'd start with function scope.

E.g. in the following snippet, `i_am_local` should not be in the completion list outside of the function. 

```sh
#!/usr/bin/env bash

hello() {
    i_am_global="hello"
    local i_am_local="hej"

    echo "in function: $i_am_global"
    echo "in function: $i_am_local"
}

hello
echo "outside function $i_am_global"
echo "outside function $i_am_local"
```

One way you might do this would be:

1. Don't add `local` variables to the symbols list when we process files
2. When asking for completions, traverse the tree upwards and collect any `local` definitions in scope

Happy to chat more about this approach offline if you're interested :)

**Comment by skovhus** [comment]
Update on file-aware symbol completion.

The grammar currently doesn't have support for sourcing as a type (neither `source ./somefile.sh` or `. ./somefile.sh `) similar to how `variable_assignment` is exposed by the grammar. A first step would be to add this to https://github.com/tree-sitter/tree-sitter-bash including an easy way to retrieve the file name.

Then we could use that for building up a tree of files that source each other, which we could use to make the symbol completion file aware.
