### ISSUE TITLE
Failed to parse expression on if clause

### ISSUE THREAD

**Issue by viltohmyst** [bash-lsp/bash-language-server#229]
I'm using neovim + spacevim with bash-language-server layer. I get a "Failed to parse expression" on this line :

if [[ "${#}" -gt 0 ]]

![Capture](https://user-images.githubusercontent.com/34679310/79745687-f3cb1e80-8332-11ea-97f6-974852056f7c.PNG)

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue – so related to the library used for parsing.

Can you see if this is already reported upstream and maybe create an issue over there: https://github.com/tree-sitter/tree-sitter-bash

**Comment by skovhus** [comment]
You can disable the error by setting the environment variable HIGHLIGHT_PARSING_ERRORS to true. 

But it means that the LSP will not really help you in this file.

**Comment by viltohmyst** [comment]
Thanks @skovhus  for your prompt reply.

I'll check if the problem still persists in other files / editors first, and check the tree-sitter-bash repo if it still does.

**Comment by david-lev** [comment]
Hi, the problem still appears in version v1.11.0
![image](https://user-images.githubusercontent.com/42866208/151519851-bc888f31-3ac8-44cb-9b05-0084dfeba776.png)
I want to continue to get highlights on errors but not on such ...
