### ISSUE TITLE
Modulus function shows parse error

### ISSUE THREAD

**Issue by icaptnbob** [bash-lsp/bash-language-server#233]
The expression if (( $count % 2 == 0 )) incorrectly shows a "Failed to parse expression" error over the "% 2"
This is a valid expression and works in the code. 

When the spaces are removed, the parse error disappears
if (( $count%2 == 0 ))

**Comment by szTheory** [comment]
I'm also seeing this issue for `((Year % 4 == 0))` where Year is a variable. Removing the spaces to `((Year%4 == 0))` fixes the parse error sad @icaptnbob mentioned, but when shellfmt runs it puts the spaces back in so the error reappears.
