### ISSUE TITLE
code completion of variables in quotes

### ISSUE THREAD

**Issue by nikita-skobov** [bash-lsp/bash-language-server#236]
consider the scenario where you have a variable defined, and then you want to use that variable from within quotation marks:

```sh
my_var="world"
echo "hello $my_var"
```

Is it possible to do code completion when you type part of that variable name, consider:
If you type `echo "hello $my_"`, can you get code completion to show up for variables that match `my_`

Is this something that the `vscode-client` extension can potentially do, or is this an issue with vscode itself?

**Comment by skovhus** [comment]
Thanks for reporting this issue. This is a feature we currently do not support, but we probably should. 

The trigger characters needs to be adjusted in the capabilities object. Besides our parser needs to understand the `$` symbol. Currently the `wordAtPoint` returns `null`... we need to figure out if the grammar should be updated or we can work around it.

**Comment by nikita-skobov** [comment]
I will take a look later today/tomorrow, and see if I can try adding this feature. Could you point me to which files/test cases are most relevant to this issue?

**Comment by skovhus** [comment]
@nikita-skobov thanks for offering your help! :) 

I actually already started having a look at this and possibly found some flaws in the `wordAtPoint` logic done in https://github.com/bash-lsp/bash-language-server/pull/192

I'll get back to you. 

But if you want to help out improving the language server and you are curious to learn how the bash parser works, then https://github.com/tree-sitter/tree-sitter-bash needs some attention. This is the parser we use, and as you see it has a bunch of parsing issues currently. Half of our issues is related to the parser. See https://github.com/bash-lsp/bash-language-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22grammar+bug%22

I can give you some pointers if you want to help out:
- https://tree-sitter.github.io/tree-sitter/
- browse some PRs here https://github.com/tree-sitter/tree-sitter-bash and see how the things are being fixed
- read through https://github.com/tree-sitter/tree-sitter-bash/blob/master/grammar.js and get and overview of how the current feature is implemented

**Comment by skovhus** [comment]
Maybe you can try out https://github.com/bash-lsp/bash-language-server/pull/237

I'll test some edges cases and document the PR with some before and after screenshots.

**Comment by nikita-skobov** [comment]
Awesome thanks, I'll give it a go.

**Comment by skovhus** [comment]
This was released as vscode extension 1.10.1 and bash-language-server 1.16.0.
