### ISSUE TITLE
File links

### ISSUE THREAD

**Issue by dufferzafar** [bash-lsp/bash-language-server#245]
I'm using the VSCode plugin (Bash IDE) and currently, there's no way to jump to files.

So for eg, with this code: I would expect that when hovering over the file path, it'll convert to a link and I'll be able to jump to the file.

```bash

source ./path/to/file

```

**Comment by skovhus** [comment]
Thanks. This is implemented as part of https://github.com/bash-lsp/bash-language-server/pull/244

If you are up for commenting on that PR that would be great. It includes some other features that you might have inputs on.

**Comment by skovhus** [comment]
This is now supported.
