### ISSUE TITLE
Parse failure for Here-Document starting with variable

### ISSUE THREAD

**Issue by ifko-ifko** [bash-lsp/bash-language-server#249]
The following construct:
```
psql <<EOSQL
${SQL}
EOSQL
```
will result in ```Failed to parse expression``` for the entire script.

Note: maybe irrelevant but got here from [Bash IDE](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode).

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
