### ISSUE TITLE
Problem with file with extension .run

### ISSUE THREAD

**Issue by maramazza** [bash-lsp/bash-language-server#250]
Hi,
Is there the possibility to remove the check for some bash file with the extension .run?
This is my settings:
"bashIde.globPattern": "**/*@(.sh|.inc|.bash|.command)"
I try with 
"bashIde.globPattern": "**/*@(.\\.sh$|.\\.inc$|.\\.bash$|.\\.command$)"
or
"bashIde.globPattern": "**/*@(.sh$|.inc$|.bash$|.command$)"
but it's not working..
How can i do it (if it's possibile) ?
Thanks

**Comment by skovhus** [comment]
The extension .run is not parsed initially. The default globpattern ensures this. 

So I believe your client (maybe vs code) detect the .run file to be bash and calls the language server. In vs code it usually tells you which kind of file it is lower right corner. Does it say bash/shell?

**Comment by maramazza** [comment]
Sorry for the not fast response
I checked and listened to your advice and so I have changed the configurations of VsCode (Files: Associations *.run --> text ) and now I have no problems
Thanks!
