### ISSUE TITLE
canot install explainshell

### ISSUE THREAD

**Issue by Luxcium** [bash-lsp/bash-language-server#251]
issue: idank/explainshell#263
 
the instruction are not the same as I am used to for some reason : 

## Configuration

To get documentation for flags on hover (thanks to explainshell), run a explainshell server and update your VS Code settings:

    "bashIde.explainshellEndpoint": "http://localhost:5000",
For security reasons, it defaults to "", which disables explainshell integration. When set, this extension will send requests to the endpoint and displays documentation for flags. We recommend using a local Docker image (see https://github.com/bash-lsp/bash-language-server/issues/180).

**Comment by skovhus** [comment]
As this is an explainshell problem, I will close this issue for the language server. A Docker image is probably the solution.
