### ISSUE TITLE
Parse error with Here Doc

### ISSUE THREAD

**Issue by brandonkal** [bash-lsp/bash-language-server#253]
Put simply, it doesn't appear that Here documents are supported.
Example script that fails to parse. I've narrowed this down to the extension. Shellcheck has no issue with this.
~~~bash
#!/bin/sh
{
  yaegi
} <<'```'
package main
import "fmt"

func main() {
	fmt.Println("Hello from Go")
}
```
~~~

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue – so related to the library used for parsing.

Can you see if this is already reported upstream and maybe create an issue over there? https://github.com/tree-sitter/tree-sitter-bash

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar.
