### ISSUE TITLE
When failing to parse a file, this language server fills the whole file with error diagnostics

### ISSUE THREAD

**Issue by rwols** [bash-lsp/bash-language-server#260]
I would suggest instead to do nothing. This hurts readability.

![Screenshot from 2020-08-06 18-56-42](https://user-images.githubusercontent.com/2431823/89560077-cab59780-d816-11ea-9561-0717ce368e88.png)

**Comment by skovhus** [comment]
Yes, we should flip the default value for this configuration option.

**Comment by rwols** [comment]
Why is this issue tagged “help wanted” when it’s a matter of flipping a Boolean as you proclaim?

**Comment by skovhus** [comment]
> Why is this issue tagged “help wanted” when it’s a matter of flipping a boolean as you proclaim?

This is an open source project where people contribute when they have time. This is all developed in our free time, but anyone can pick this ticket up and make a PR.

**Comment by skovhus** [comment]
I see that you are using Sublime, so you can simply set the desired configuration as an environment variable.

https://github.com/bash-lsp/bash-language-server/blob/master/server/src/config.ts#L19

**Comment by rwols** [comment]
Apologies for coming across as blunt. Thanks for the fix.
