### ISSUE TITLE
Provide a way to disable logging

### ISSUE THREAD

**Issue by akurtakov** [bash-lsp/bash-language-server#273]
I haven't found a way to disable logging for the server.

**Comment by skovhus** [comment]
> I haven't found a way to disable logging for the server.

Which logging would you like to disable?

**Comment by akurtakov** [comment]
All of:


    [Log] Initialized server v. 1.16.1 for file:///~~~~~~~~~~
    [Log] Analyzing files matching glob "**/*@(.sh|.inc|.bash|.command)" inside ~~~~~~~~~
    [Log] Glob resolved with 1 files after 0.055 seconds
    [Log] Analyzing file:///~~~~~~~~~~~.sh
    [Log] Analyzer finished after 0.068 seconds
    [Log] onDocumentHighlight 11:13 word=null
    [Log] onDocumentHighlight 11:13 word=null
    [Log] onDocumentSymbol
    [Log] onDocumentHighlight 18:28 word="MISSING_ENVS"
    [Log] onHover 11:12 word=null
    [Log] onDocumentHighlight 11:13 word=null
    [Log] onHover 8:13 word=null
    [Log] onDocumentHighlight 8:13 word=null
    [Log] onHover 16:4 word="eval"
    [Log] onDocumentHighlight 16:2 word="eval"
    [Log] onHover 9:1 word=null

**Comment by skovhus** [comment]
@vrubezhny @akurtakov I'm trying to prioritize solving this. But I'm curious how common is it that you are actually annoyed by these logs? For the VS Code client you never see the logs unless you specifically go to "output -> Bash IDE".

**Comment by akurtakov** [comment]
It would be nice to have as Eclipse LSP4E defaults to print everything to the console when developing so there is ton of lsp messages but it's not end user visible thing.

**Comment by skovhus** [comment]
> Eclipse LSP4E defaults to print everything to the console

That’s odd. Can you paste a screenshot?

**Comment by akurtakov** [comment]
Here it is 
![image](https://user-images.githubusercontent.com/574788/206751360-9a245d4e-6ba1-49e2-9cab-5dfdc2018ebf.png)

**Comment by skovhus** [comment]
@akurtakov some weeks ago a new version of the server was released that supports configuring logging. See more documentation here: https://github.com/bash-lsp/bash-language-server#logging

Let me know if this works for you. You cannot currently disable all logging, but you can set the logging level to error, which I hope solves the problem for you.
