### ISSUE TITLE
Incorrect Hover Documentation Shown

### ISSUE THREAD

**Issue by hak33m16** [bash-lsp/bash-language-server#278]
When a function is created that has the same name as an executable on a user's path (e.g. something like 'ls'), when you hover over the name of that function at the definition site or wherever it's being used, the man page for that executable is shown

Example:
```
ls() {
  echo "TEST"
}

ls
```

Hovering over `ls` in both of these situations will result in the error I mentioned above happening (worth noting that this doesn't break the "Go to Definition" feature, so it's really just an aesthetic issue)

**Comment by skovhus** [comment]
Good catch. Let me know if you want to help fix the issue.

**Comment by hak33m16** [comment]
Sure, I'd definitely be willing to take a crack at it this weekend

**Comment by skovhus** [comment]
> Sure, I'd definitely be willing to take a crack at it this weekend

Thanks, that would be great! 👏

**Comment by hak33m16** [comment]
Do you have any form of IRC/Discord/communication channel for this project I could contact you through, in case I get stuck on something?

**Comment by skovhus** [comment]
We do not have any forum/channels, but feel free to ping me here or in a draft PR. :)
