### ISSUE TITLE
Retrieving definition not supported for filetype 'sh'

### ISSUE THREAD

**Issue by Victordongy** [bash-lsp/bash-language-server#280]
I am using `vim` 8, and have compiled my vim following the instruction as 

1. install plugin `prabirshrestha/vim-lsp`
2. add the configuration as 
```
if executable('bash-language-server')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'bash-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'bash-language-server start']},
        \ 'allowlist': ['sh'],
        \ })
endif
```

However, if I use `:LspDefinition`, I still encountered the following error : 

> Retrieving declaration not supported for filetype 'sh'

Any idea to fix this ? Or did I miss any step ?

**Comment by skovhus** [comment]
Please raise this in the vim-lsp community.
