### ISSUE TITLE
Confusion about using bash-language-server through Bash IDE extension on vscode

### ISSUE THREAD

**Issue by Justin1904** [bash-lsp/bash-language-server#292]
I am trying to use bash-language-server in VSCode, and there is the [Bash IDE extension](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode#:~:text=Bash%20IDE%20Visual%20Studio%20Code%20extension%20utilizing%20the,its%20grammar%20for%20Bash%20and%20supports%20explainshell%20integration.) that seems to achieve this. However, I am confused if I need to install bash-language-server on my own and then install the VSCode extension, or is the VSCode extension all that I need?

**Comment by rcjsuen** [comment]
> However, I am confused if I need to install bash-language-server on my own and then install the VSCode extension, or is the VSCode extension all that I need?

@Justin1904 Installing the extension should be all you need to do.

**Comment by skovhus** [comment]
Yes, the extension is all you need. The language server is embedded into the extension. 

Let us know how we could make this clearer in the documentation.

**Comment by Justin1904** [comment]
Thanks for the promptness! I don't have anything very specific in mind, adding statements like "Bash IDE extension comes bundled with bash-lsp, so you don't have to install bash-lsp separately" would appear as a bit too specific and out of context for many folks I guess.

I could describe what part of the doc makes me confused though - Looking at Bash IDE description, it says "VScode extension utilizing bash-language-server ...", and here I thought maybe it's dependent on bash-lsp, so I go into this repo, and sees that "Bash IDE" is listed one of the "client" ([see here](https://github.com/bash-lsp/bash-language-server#clients)), which gives me the impression that the extension itself doesn't have a language-server bundled with it. It could be just me overthinking a bit here.
