### ISSUE TITLE
Memory consumption in big repository

### ISSUE THREAD

**Issue by backdround** [bash-lsp/bash-language-server#297]
version: 1.17.0
editor: nvim
plugin: coc

I had full of memory consumption, when try to edit bash scripts in repo with linux (kernel) submodule within. How can i ignore some paths when using language server?

![image](https://user-images.githubusercontent.com/17349169/123612775-886cbe80-d80b-11eb-90f1-152e3d145d29.png)

E.g. If i use ccls server in the same repository, i dont have memory consumption like that.

**Comment by skovhus** [comment]
A more performant, robust and stable analyzer has been released as version 3.3.0 (which is part of the latest VSCode extension 1.17.0). You can find more details in https://github.com/bash-lsp/bash-language-server/pull/569

I'm very curious if you can test it out and see how it works for you. Thanks in advance :)

**Comment by skovhus** [comment]
Note that we have also [fixed a bug causing memory leaks and high CPU usage for workspaces with many files](https://github.com/bash-lsp/bash-language-server/pull/661
) – this has been released as bash-language-server@4.2.5 and the vscode extension 1.26.0.
