### ISSUE TITLE
The local variable is not listed as a candidate for auto-completion in Doom-Emacs when bash-language-server is enabled

### ISSUE THREAD

**Issue by ylorn** [bash-lsp/bash-language-server#311]
### Doom-Emacs settings:

default settings in `~/.doom.d/init.el`:

```emacs-lisp
(sh
 +lsp)
```

### What happened:

When a variable is declared as `local`,  the variable won't appear in the auto-completion list:

<img width="1440" alt="129437656-fc7e6df3-8f9b-423e-aadc-05ffc6db5f5c" src="https://user-images.githubusercontent.com/1502810/129736089-d633ebc1-9c24-4c3e-958a-0b34257a6a21.png">

However, when removing the `local` directive and make it a global variable, the variable is listed as a valid auto-completion candidate as expected:

<img width="1440" alt="129437667-36448ab8-6ceb-4b05-9dbc-7d79dadfa94a" src="https://user-images.githubusercontent.com/1502810/129736303-9404733d-a81e-43bf-b620-b4f304f82b4c.png">

The lsp log:

> Command "/opt/homebrew/bin/bash-language-server start" is present on the path.
> Command "/opt/homebrew/bin/bash-language-server start" is present on the path.
> Command "/opt/homebrew/bin/bash-language-server start" is present on the path.
> Command "/opt/homebrew/bin/bash-language-server start" is present on the path.
> Found the following clients for /Users/****/Desktop/test.sh: (server-id bash-ls, priority 9999)

### Question

Opened [a ticket](https://github.com/hlissner/doom-emacs/issues/5381) in Doom Emacs repo and it seems it uses the bash-language-server without any extra configuration. 

I am wondering if this is a bug in bash-language-server, or is there any additional configuration I need to tweak to make the auto-completion work properly.

Thanks

**Comment by skovhus** [comment]
A much better heuristic for symbol resolution has been released as bash-language-server@4.2.0 and for vscode in the latest extension 1.24.0. It opens up for implementing renaming of symbols, and I also believe this solves the issue here.

Please let me know if it works for you or if you have any feedback to the new version.
