### ISSUE TITLE
VSCODE: add check if function exists in code

### ISSUE THREAD

**Issue by hugoabreu1002** [bash-lsp/bash-language-server#314]
Hello, 

I am using bash-IDE for VSCODE and missing a feature to check if a given a call to a function is correct.

Let's say there should have function in the script, that is commented or isn't defined and you try to call this function:

```
#function fooFunc(){
#   local foovar
#   foovar=$1
#   echo "$foovar"
#}

fooFunc "hello foo"
```

The IDE as it is now, doesn't see this as a mistake or give any warning...

**Comment by skovhus** [comment]
We now have ShellCheck integration. Please follow https://github.com/koalaman/shellcheck#installing and update your vscode installation.
