### ISSUE TITLE
[FeatureRequest] Allow to configure glob options

### ISSUE THREAD

**Issue by loynoir** [bash-lsp/bash-language-server#316]
### Feature Request
Would be nice to be able to configure glob options. 😄

https://github.com/bash-lsp/bash-language-server/blob/8a5115d129208d9ac0e18d4eaf7fbc6c384f325f/server/src/util/fs.ts#L22

### Use case
For example, glob options `follow: true`.

I use `pnpm` to manage shell dependency to avoid [doppelgangers](https://rushjs.io/pages/maintainer/package_managers/#considerations-for-pnpm). 😄

But, `pnpm` use symlink...

### Alternative
Glob here is about sourcing files, existing sourcing file pattern allowed by `shellcheck`.

```sh
# src/foo.sh

# shellcheck source-path=../node_modules/MODULE_NAME
BASE=/path/to/node_modules/MODULE_NAME
source "${BASE}"/lib/bar1.sh
source "${BASE}"/lib/bar2.sh
...
```

Maybe when found syntax
```sh
source ${VARIABLE}/SUBPATH
```
Let `bashls` source 
```js
path.join(
  path.resolve(
    path.dirname(CURRENTFILE), 
    SHELLCHECK_SOURCE_PATH_ELEMENT
  ),
  SUBPATH
)
```

**Comment by skovhus** [comment]
A more performant, robust and stable analyzer has been released as version 3.3.0 (which is part of the latest VSCode extension 1.17.0). You can find more details in https://github.com/bash-lsp/bash-language-server/pull/569

I'm very curious if you can test it out and see how it works for you. We do not allow the glob options to be configured yet. 

#244 could improve how we do scope aware completions based on sourced files. 

Thanks in advance :)
