### ISSUE TITLE
crash on glob error [Error: EACCES: permission denied,

### ISSUE THREAD

**Issue by hans-d** [bash-lsp/bash-language-server#317]
When running on mac, when the glob encounters a file or directory that is not readable by the current user.

```
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "Initialized server v. 1.17.0 for file:///Users/<xxxx>"))
[server-notification] Wed Dec  1 21:06:26 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "Analyzing files matching glob \"**/*@(.sh|.inc|.bash|.command)\" inside /Users/<xxxx>/"))
[stderr] glob error [Error: EACCES: permission denied, scandir '/Users/<xxxx>/log/events.log'] {
[stderr]   errno: -13,
[stderr]   code: 'EACCES',
[stderr]   syscall: 'scandir',
[stderr]   path: '/Users/<xxxx>/log/events.log'
[stderr] }
[internal] Wed Dec  1 21:06:55 2021:
(:message "Connection state changed" :change "killed: 9\n")
```
(captured from emacs environment)

**Comment by skovhus** [comment]
A more performant, robust and stable analyzer has been released as version 3.3.0 (which is part of the latest VSCode extension 1.17.0). You can find more details in https://github.com/bash-lsp/bash-language-server/pull/569

I'm very curious if you can test it out and see how it works for you. I believe it should fail if it finds permission issues.

Thanks in advance :)
