### ISSUE TITLE
Can we run this server in bash terminal?

### ISSUE THREAD

**Issue by parrotcar00** [bash-lsp/bash-language-server#321]
I wanted to run this server in my bash terminal for day to day usage i.e. not run this inside vscode or vim or anything else but directly running it in bash prompt as a autocompletion utility. I couldn't find any instructions for it.

**Comment by skovhus** [comment]
This should do the trick:
```
npm i -g bash-language-server
bash-language-server start
```

**Comment by parrotcar00** [comment]
I did this:
```$npm i -g bash-language-server```

```$npx bash-language-server start```

and then I tried doing "cat <TAB>" to see if something new is happening but I don't see any evidence of language server kicking in - I didn't see any dropdowns or anything more than the usual tab autocomplete.

I then tried doing this:
 ```$npx bash-language-server start &```
and thought maybe the language-server needs to run in background but I still didn't get any completion prompts in my terminal.

**Comment by skovhus** [comment]
bash-language-server provides completion and other features for clients such as VSCode, Eclipse, Emacs. See the complete list here: https://github.com/bash-lsp/bash-language-server#clients

It unfortunately cannot provide completions for your terminal.
