### ISSUE TITLE
extglob syntax not understood in case statement

### ISSUE THREAD

**Issue by dseynhae** [bash-lsp/bash-language-server#323]
For a Bash case statement, the individual cases can be matched based on extended glob syntax; Consider the `/+([a-z])` expression in the first branch:

```bash
declare -a opts=()
declare -a files=()

shopt -s extglob

for o in "$@"; do
	case $o in
	/+([a-z]))
		opts+=("$o")
		;;
	*)
		files+=("$o")
		;;
	esac
done
```

This piece of code works perfectly when executing in a script, however in VS Code with the Bash Language Server extension, it is flagged as a problem:

![image](https://user-images.githubusercontent.com/54114043/152064090-9985124b-f2e9-484a-aa6f-51cb2762b524.png)

This problem will not be flagged when turning off the error highlighting; But kind of defeats the purpose and benefit of having a language server checking your code:

![image](https://user-images.githubusercontent.com/54114043/152064488-1397a81a-2989-4aa6-95ba-d6e83ed626d5.png)

**Comment by skovhus** [comment]
Thanks for reporting this.

Unfortunately this is an issue with the underlying parser and grammar: https://github.com/tree-sitter/tree-sitter-bash

It would be great if we could find a better parser.

**Comment by dseynhae** [comment]
I see, I found this [bug report](https://github.com/tree-sitter/tree-sitter-bash/issues/69) indeed, and voted it up...

I am a little surprised that not more people run into this: the true power of a Bash `case` is when using branches based on `extglob` branches...

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
