### ISSUE TITLE
Wrong description on hover for `tr`

### ISSUE THREAD

**Issue by syheliel** [bash-lsp/bash-language-server#341]
I'm working on WSL2 and `tr` is recognized as `trap`.
![image](https://user-images.githubusercontent.com/45957390/158107777-73767b35-0ece-4262-baba-647409ef6b7d.png)
 To produce it. Just create a new `.sh` file, and  type:
```
tr '\n' '\0'
```

**Comment by syheliel** [comment]
Maybe PR #281 has fixed it

**Comment by skovhus** [comment]
At least it should be fixed in 3.3.1.

https://github.com/bash-lsp/bash-language-server/pull/577
