### ISSUE TITLE
KindInfo in auto-completion seems to be messed up

### ISSUE THREAD

**Issue by deathaxe** [bash-lsp/bash-language-server#343]
When typing `if` this language server returns `[{'label': 'if', 'data': {'name': 'if', 'type': 2}, 'kind': 11}]`

The `11` means `CompletionItemKind.Unit`, but it should return `14` `CompletionItemKind.Keyword`.

![grafik](https://user-images.githubusercontent.com/16542113/160891128-ce0ea402-d83a-4754-97a3-0b207a49fe31.png)

A look at server.ts reveals it being typed as `SymbolKindInfo.Interface`, which is valued `11` as well.

https://github.com/bash-lsp/bash-language-server/blob/6ee982669df77a62e2f8588c3634aa28a6226ce2/server/src/server.ts#L386

I have a feeling to see 2 errors here:

1. Instead of `SymbolKindInfo` I think `CompletionItemKind` should be used in all those lines around L386.
2. The kind of reserved words should probably be `CompletionItemKind.Keyword` instead of `SymbolKindInfo.Interface`.

I found a `symbolKindToCompletionKind()` but it is missing a translation for `SymbolKindInfo.Keyword` to `CompletionItemKind.Keyword` thus returning `CompletionItemKind.Text` in such cases. But it is not even applied for completions.

**Comment by skovhus** [comment]
Thanks. I'm pretty sure a lot of the `kind` types were not carefully selected. So we will happily accept a PR fixing these. :)

**Comment by deathaxe** [comment]
I am not a TypeScript dev. I managed to investigate the stuff, but I've never used yarn or whatever dev stuff is used here. I am too busy with other stuff to be wanting to dig into that stuff to get build systems working or whatever is needed.
