### ISSUE TITLE
Error after updating to version 3.0.0

### ISSUE THREAD

**Issue by ryan-WORK** [bash-lsp/bash-language-server#393]
I am using:
- nvim-0.7.0
- bashls-3.0.0

The error I am getting is:
`bashls: -32603: Request textDocument/documentHighlight failed with message: Cannot read properties of undefined (reading 'rootNode')`

This error presented itself after updating `bashls` to the latest version `3.0.0` from `2.1.0` 
![Screen Shot 2022-05-13 at 2 16 47 PM](https://user-images.githubusercontent.com/42385438/168391203-036c3876-9439-425b-be45-bedc5bccf975.png)

Is version `3.0.0` in preparation for nvim 0.8.0?

**Comment by skovhus** [comment]
Thanks for reporting this. The issue should be fixed in 3.0.2. Please let us know if it works for you.

**Comment by PolSust** [comment]
I'm getting this error on version 3.0.3

I'm using LunarVim and nvim version 0.8.0
