### ISSUE TITLE
Why even my $PATH contains path to `shellcheck` it doesn't work out of the box?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [bash-lsp/bash-language-server#415]
- `$PATH` = `/home/emilyseville7cfg/.dotnet:/home/emilyseville7cfg/.local/bin:/home/emilyseville7cfg/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
- `which shellcheck` = `/usr/bin/shellcheck`

But when I open any .sh script I obtain no linting:

![image](https://user-images.githubusercontent.com/42812113/170884210-4205cd7d-ad68-4c1d-adbb-41cea97afea8.png)

The workaround is:

```json
// Settings in here override those in "LSP-bash/LSP-bash.sublime-settings"

{
    "env": {
        "SHELLCHECK_PATH": "/usr/bin/shellcheck"
    }
}
```

**Comment by skovhus** [comment]
From 3.2.0 we now automatically find the binary. Previously this was only enabled after using the configuration option.

Let me know if it works for you.

**Comment by EmilySeville7cfg** [comment]
Thanks for a response. But I don't use Sublime Text now to check it. :(
