### ISSUE TITLE
Shellcheck: Possibility to provide severity option

### ISSUE THREAD

**Issue by mambusskruj** [bash-lsp/bash-language-server#424]
Not sure if it is not presented already, but. 

Shellcheck has `--severity` option with which I can tell to show only `errors` and `warnings` messages, but not `info`. Can't find possibility to set this option with bash-language-server.

**Comment by a5ob7r** [comment]
ShellCheck reads `SHELLCHECK_OPTS`, which is an environment variable to pass some arguments to it.

How about you set the variable like `SHELLCHECK_OPTS='--severity=error'`?

**Comment by mambusskruj** [comment]
@a5ob7r 
Works like a charm, thank you!
