### ISSUE TITLE
shellcheck :: Option to disable activation

### ISSUE THREAD

**Issue by lcrockett** [bash-lsp/bash-language-server#432]
Cheers on the (long awaited) feature to include `shellcheck` in `bashls`.

My personal setup is to leverage `null-ls` in activating / de-activating `shellcheck` whenever I feel like i'd want to use it. Considering `bashls` automatically gets activated via `nvim-lspconfig`, and therefore `shellcheck`, I have no way anymore to disable `shellcheck` functionality on the fly.

Are there options available or planned to toggle activating `shellcheck` when using `bashls` ?

Cheers

**Comment by b0o** [comment]
This is possible by setting `SHELLCHECK_PATH` to the empty string. With lspconfig:

```lua
require('lspconfig').bashls.setup {
  cmd_env = { SHELLCHECK_PATH = '' },
}
```

[Relevant section of the code.](https://github.com/bash-lsp/bash-language-server/blob/main/server/src/config.ts#L5-L6)

**Comment by lcrockett** [comment]
Works like a charmadillo, cheers !
