### ISSUE TITLE
no information on hover for `mapfile`

### ISSUE THREAD

**Issue by ayushnix** [bash-lsp/bash-language-server#437]
There's no information being displayed when I execute `vim.lsp.buf.hover()` on some bash keywords like `mapfile`. Is this expected?

neovim version: 0.7.0
bash-language-server version: 3.0.3

I've confirmed that bash-language-server is active on the bash buffer I'm working on by using `:LspInfo` which shows

```
 2 client(s) attached to this buffer: 
 
 Client: bashls (id: 1, pid: 424841, bufnr: [1])
 	filetypes:       sh
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             bash-language-server start
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       sh, lua, yaml, yaml.ansible
 	autostart:       false
 	root directory:  /home/user
 	cmd:             nvim
 
 Configured servers list: bashls
```

**Comment by skovhus** [comment]
Can you provide a bash file as an example?

**Comment by skovhus** [comment]
@ayushnix please reopen if you can provide a code example.

**Comment by Mrestof** [comment]
Hello. In my code I use this functionality of bash too. I would like to see support for `readarray` and `mapfile` keywords from bash. Also worth noting that their syntax is a bit tricky, because they create a new variable if it did not exist before.
[stackoverflow example](https://stackoverflow.com/a/54561526)

**Comment by elder-n00b** [comment]
VSCode sent me here clicking "Repository" for extension
~~~
mads-hartmann.bash-ide-vscode v1.39.0
Last updated 2023-09-15, 12:13:33
~~~

Code example? Code example:
~~~
#!/bin/bash
readarray
mapfile
printf
~~~
Hover `printf`, help. Hover the other two, not.

It's not clear to me:
is the extension correct in pointing here?
is this issue only in the extension and not the language server proper?
