### ISSUE TITLE
No completions for command options and Bash builtins

### ISSUE THREAD

**Issue by EmilySeville7cfg** [bash-lsp/bash-language-server#454]
# Environment

Emacs: 27.1

# Steps to reproduce

- `sudo apt install nodejs`
- `sudo apt install npm`
- `sudo npm i -g bash-language-server`
- `M-x package-install RET lsp-mode`
- `M-x lsp-install-server RET bash-ls`
- Open .sh file and see no completion for bash builtins and command options on `C-M i`:
  - Nothing is suggested for `sho` (shopt is expected)
  - Nothing is suggested for `sed --` (sed options are expected)

![image](https://user-images.githubusercontent.com/42812113/178142544-16c643cb-55d2-4641-ac02-0f8003c1ddde.png)

**Comment by skovhus** [comment]
Command options is currently not supported, but bash builtins should work. Can you still reproduce this with the latest version of bash-language-server?

**Comment by skovhus** [comment]
Correction, actually command options can be shown if you integrate with explainshell (see https://github.com/bash-lsp/bash-language-server/issues/180)
