### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mr-Hacks** [bash-lsp/bash-language-server#472]
- Issue Type: `Performance`
- Extension Name: `bash-ide-vscode`
- Extension Version: `1.14.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/INVENTOR/AppData/Local/Temp/mads-hartmann.bash-ide-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by skovhus** [comment]
Note that we have also [fixed a bug causing memory leaks and high CPU usage for workspaces with many files](https://github.com/bash-lsp/bash-language-server/pull/661
) – this has been released as bash-language-server@4.2.5 and the vscode extension 1.26.0.
