### ISSUE TITLE
Treating PKGBUILD as bash files

### ISSUE THREAD

**Issue by WhyNotHugo** [bash-lsp/bash-language-server#473]
`PKGBUILD`s  are basically bash scripts. bashls errors:

> SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.

Can I somehow indicate to the language server when starting is "this file is a bash script"? Perhaps a cli flag?

**Comment by startnoob** [comment]
Same problem, and also a bunch of
> SC2034: xxx(pkgrel, license, etc. ) appears unused. ......

but those values are necessary for PKGBUILD.

**Comment by adoyle-h** [comment]
It should be fixed by #536

**Comment by WhyNotHugo** [comment]
Yeah, I think this would fix this issue.

The problem @startnoob will still be around, but that sounds like a separate issue, and I'm not sure how to address it.

**Comment by skovhus** [comment]
@WhyNotHugo did you try the latest language server?
