### ISSUE TITLE
Build instructions for VScode extension?

### ISSUE THREAD

**Issue by sergei-dyshel** [bash-lsp/bash-language-server#487]
Just tried to checkout and build vscode extension in `vscode-client` dir.  Looks like it's kind of neglected/not maintained:

1. No typescript dependency.
2. No background compilation task when developing in vscode, no even npm script defined.
3. When trying to compile, get lots of errors like

```
server/src/util/__tests__/sh.test.ts:33:5 - error TS2304: Cannot find name 'expect'.

33     expect(lines[1]).toContain('list directory contents')
```

is there some another branch/fork I'm supposed to use?

**Comment by skovhus** [comment]
Thanks for the interest in contributing to the vscode extension.

Did you follow the [development guide](https://github.com/bash-lsp/bash-language-server/blob/main/docs/development-guide.md)? I also just added a [CONTRIBUTING.md](https://github.com/bash-lsp/bash-language-server/blob/main/CONTRIBUTING.md) file with a link to the development guide.

This is a mono repository, so you should develop it from the root folder. There you will find the npm scripts that you would expect. 

Let me know if this solves the issue for you.
