### ISSUE TITLE
function and variable names with some word-separating characters are not properly recognized during hinting

### ISSUE THREAD

**Issue by mike-chen-f8** [bash-lsp/bash-language-server#49]
Function names such as `test:1` and `test-1-1` shows up as `test` on code hinting.

`test_1` shows up properly.

**Comment by mads-hartmann** [comment]
Thanks for reporting this @mike-chen-f8. This is very likely a problem with the underlying tree-sitter grammar. I'll have a look over the weekend 👍

**Comment by skovhus** [comment]
`test-1-1` comletion works now. But `test:1` does not.

But note that in POSIX sh, naming functions outside [a-zA-Z_][a-zA-Z0-9_]* is undefined.
