### ISSUE TITLE
Recognise `: "${VARIABLE:="default"}"` as variable definition

### ISSUE THREAD

**Issue by Frederick888** [bash-lsp/bash-language-server#519]
`:` does argument expansion and retains the side effects.
A common usage is to define default values of environment variables, e.g. `: "${VARIABLE:="default"}"`.

It seems this is only recognised as variable reference at the moment. It would be nice to treat them as definitions as well.

**Comment by skovhus** [comment]
Could you elaborate a bit so I'm clear what the behvaiour you expect here?

```bash
VARIABLE=

foo="${VARIABLE:="default"}"

echo $foo
```

**Comment by Frederick888** [comment]
@skovhus Sure. I usually use this syntax to set default values of variables. For example:

```sh
#!/usr/bin/env bash

: "${FILE_PATH:="/default/file"}"

printf 'Printing %s\n' "$FILE_PATH"
cat "$FILE_PATH"
```

```sh
$ ./file_printer.sh
Printing /default/file
cat: /default/file: No such file or directory

$ FILE_PATH="$HOME/file_printer.sh" ./file_printer.sh
Printing /home/frederick/file_printer.sh
#!/usr/bin/env bash

: "${FILE_PATH:="/default/file"}"

printf 'Printing %s\n' "$FILE_PATH"
cat "$FILE_PATH"
```

At the moment it seems `: "${FILE_PATH:="/default/file"}"` is only registered as a reference to `FILE_PATH` but not a definition.

**Comment by skovhus** [comment]
@Frederick888  this is now supported in the language server 4.6.0 (will be released to vscode soon). 

Let me know if you have other ideas for future improvements by creating GitHub issues. Thanks!
