### ISSUE TITLE
FR: shellcheck: option to force a shell dialect

### ISSUE THREAD

**Issue by chrisgrieser** [bash-lsp/bash-language-server#527]
Regarding the missing handling of zsh (e.g. #252), there is commonly the small trick to force shellcheck to lint a zsh file anyway, by using the argument `--shell=bash`. Since most of the rules apply to bash as well as zsh, this isn't that big of a problem.

With linter integration plugins for code editors, you can do this by changing the command that is used; however, I can't see how I can do that with this language-server.

**Comment by skovhus** [comment]
This was done in https://github.com/bash-lsp/bash-language-server/pull/536

Please reopen if this didn't solve your usecase.
