### ISSUE TITLE
replace `request` and `request-promise-native` with better http client

### ISSUE THREAD

**Issue by lakshya-sky** [bash-lsp/bash-language-server#534]
Both the packages have been deprecated and needs to be replaced with a better one. here is the alternative list. 
https://github.com/request/request/issues/3143

I think we should use `undici` as it is from node devs.

What are your opinions?

**Comment by skovhus** [comment]
Good point. As fetch is already shipped with experimental support in node 18, then I'm leaning towards node-fetch. If we need any special features then axios is a very solid choice.
