### ISSUE TITLE
Symbols disappear in zsh syntax, tree-sitter

### ISSUE THREAD

**Issue by hinell** [bash-lsp/bash-language-server#539]
```bash
# script.zsh
${(F)var[@]}
${var[@]}
```

```syntax
// Syntax tree error for script.zsh
(program
    (ERROR 
        (subshell (command name: (command_name (word))))
        …
    )
)
    
(program
    (command name: 
        (command_name (expansion (subscript name: (variable_name) index: (word))))
    )
)
```
<details>
<summary>Steps to reproduce syntax tree error</summary>

```js
let Parser = require("tree-sitter");
let Bash   = require("tree-sitter-bash");

let parser = new Parser();
    parser.setLanguage(Bash);
let r;
    r = parser.parse('${(F)FOO_ARR[@]}') 
    console.log(r.rootNode.toString());

    r = parser.parse('${FOO_ARR[@]}') 
    console.log(r.rootNode.toString());

```
</details>

Is this LSP server supposed to provide support for zsh?  It seems like that [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash)  fails to recognize [ZSH Parameter Expansion Flags]. Because of that, symbols after these two lines above aren't shown in the symbol menu navigation in the VS Code. The syntax error appears both in `wasm` and `native` tree-sitter bindings.

Here is a nother example. The following script "hides" symbols below the `echo` lines if double quotes surround the variable expansion: `fn()` becomse hidden in the `Go to symbol`  menu of the VS Code: 
```sh
echo "${(F)FOO_ARR[@]}" # Quotes hide fn symbol, if removed, fn show again
fn(){ ; }
```

[ZSH Parameter Expansion Flags]: https://zsh.sourceforge.io/Doc/Release/Expansion.html
[tree-sitter-bash]: https://github.com/tree-sitter/tree-sitter-bash
[tree-sitter]: https://github.com/tree-sitter/node-tree-sitter
[bash-language-server]: https://github.com/bash-lsp/bash-language-server
[Tree Sitter WASM binding]: https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/README.md

## Diagnostics 
```
Bash IDE v1.14.0
VS Code 1.73
```

## Workaround
The `${(F)FOO_ARR[@]}` may be replaced by `print -l `$FOO_ARR`

**Comment by hinell** [comment]
There is also a related issue to tree-sitter:
* https://github.com/tree-sitter/tree-sitter-bash/issues/93

**Comment by skovhus** [comment]
The bash-language-server is supporting bash, not zsh as [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) lacks the support.
