### ISSUE TITLE
go-to-definition does not work for loop variables

### ISSUE THREAD

**Issue by diminutivesloop** [bash-lsp/bash-language-server#545]
Given the following code:
```bash
GREETING="Hello"
for i in 1 2 3 4 5
do
 echo "$GREETING $i"
done
```
go-to-definition works for `$GREETING` but not for `$i`.

**Comment by skovhus** [comment]
Thanks for reporting this.

I've looked into this, and the [grammar](https://github.com/tree-sitter/tree-sitter-bash) defines `i` on the second line as a `variable_name` and not a `variable_assignment` with a named node. We could hack around this by checking if the parent is a `for_statement`, but it would be great if the grammar supported this natively instead.
