### ISSUE TITLE
Option to exclude directories for go-to-definition

### ISSUE THREAD

**Issue by diminutivesloop** [bash-lsp/bash-language-server#546]
I would like an option to exclude directories from consideration for go-to-definition. This would help particularly in JavaScript projects where go-to-definition will sometimes find definitions in shell scripts included within installed dependencies which are almost never relevant.

**Comment by skovhus** [comment]
The current behaviour is pretty crude. Instead of excluding directories, I'm leaning towards making the completions aware of the sourced files. See the prototype in https://github.com/bash-lsp/bash-language-server/pull/244

Would that solve your need?

**Comment by skovhus** [comment]
@diminutivesloop can you try the new 4.1.0 version (also released as a new VS Code extension)?

**Comment by diminutivesloop** [comment]
Seems to be working. Thanks!

**Comment by diminutivesloop** [comment]
I did notice that "Go To References" shows results from other files irrespective of sourcing commands, but only if other files have been opened since VSCode was last reloaded. That behavior doesn't directly impact this issue but I wanted to flag it in case it's a bug.

**Comment by skovhus** [comment]
> I did notice that "Go To References" shows results from other files irrespective of sourcing commands, but only if other files have been opened since VSCode was last reloaded

The previous behavior actually did a background analysis for all files matching the configurable glob. If the files found had a bash/sh shebang then they would be included in the global symbols. But thanks for testing the new server. 🙌🏼
