### ISSUE TITLE
go-to-definition doesn't jump to closest same-file definition

### ISSUE THREAD

**Issue by diminutivesloop** [bash-lsp/bash-language-server#548]
When using go-to-definition on a variable with multiple definitions, if the VSCode setting `editor.gotoLocation.multipleDefinitions` is set to "goto", the jumped-to definition is frequently either in a different file or if it is in the same file it's not the closest one. However if `editor.gotoLocation.multipleDefinitions` is set to "peek" then the selected definition in the peek view is the closest in-file definition. Ideally "goto" should jump to whatever the selected "peek" definition would be which should be the closest same-file definition.

**Comment by skovhus** [comment]
A much better heuristic for symbol resolution has been released as `bash-language-server@4.2.0` and for vscode in the latest extension 1.24.0. I believe this solves the issue here.

@diminutivesloop Please let me know if it works for you or if you have any feedback to the new version.

**Comment by diminutivesloop** [comment]
@skovhus As best as I can tell it's working fine.
