### ISSUE TITLE
Bash IDE (VSCode) doesn't work on macOS

### ISSUE THREAD

**Issue by andynameistaken** [bash-lsp/bash-language-server#554]
- OS Version: `11.7.1 `
```
❯ brew list --versions shellcheck
shellcheck 0.8.0
```
- VSCode Version: 1.73.1
- error is not shown in:
![image](https://user-images.githubusercontent.com/15692002/203755735-083d4b7d-8fe5-4abb-ae51-c100c31532bd.png)

**Comment by skovhus** [comment]
Thanks for reporting this. The release of the vscode client supporting this was a bit silent, and turns out, also lacking the configuration option. That has now been fixed and I'll release it shortly. Stay tuned.

**Comment by skovhus** [comment]
A new version of the extension has been released. Let me know if it works for you. You might need to restart vs code until you see the new version.
