### ISSUE TITLE
Outlining is broken by "here document"

### ISSUE THREAD

**Issue by dthomash** [bash-lsp/bash-language-server#57]
Here document explanation: https://en.wikipedia.org/wiki/Here_document#Unix_shells

Simplified version of source that shows the problem:

```
methodname() {
	cat > file.txt << EOF
File contents
EOF
	echo "I'm still here"
}
```

When you minimize the method, it only minimizes until it hits the second EOF. Expected behavior is to minimize to the ending curly brace. I'm using vscode.

**Comment by mads-hartmann** [comment]
@havemeyerd Thanks for reporting this. I'll have a look

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
