### ISSUE TITLE
How to override shellcheck options?

### ISSUE THREAD

**Issue by dmilith** [bash-lsp/bash-language-server#578]
I'd like to either:
- Override LSP-bash that's forcing enabling shellcheck without any options,
- be able to provide these options to shellcheck some normal way
```
--exclude=SC2034,SC1090,SC1091,SC2164,SC2181,SC2154,SC2004,SC2016,SC2086,SC2048,SC2148
```

**Comment by dmilith** [comment]
RIght now I defined my own LSP client this way:

```
{
	"show_diagnostics_panel_on_save": 0,
	"show_code_lens": "phantom",
	"show_inlay_hints": true,
	"clients":
	{
		"LSP-shellcheck": {
			"enabled": true,
			"command": [
				"/opt/homebrew/bin/node",
				"/opt/homebrew/bin/diagnostic-languageserver",
				"--stdio"
			],
			"selector": "source.shell",
			"initializationOptions": {
				"linters": {
					"shellcheck": {
						"command": "/opt/homebrew/bin/shellcheck",
						"debounce": 100,
						"args": [
							"--format=json",
							"--shell=sh",
						    "--exclude=SC2034,SC1090,SC1091,SC2164,SC2181,SC2154,SC2004,SC2016,SC2086,SC2048,SC2148",
							"-"
						],
						"offsetLine": 0,
						"offsetColumn": 0,
						"sourceName": "shellcheck",
						"formatLines": 1,
						"parseJson": {
							"line": "line",
							"column": "column",
							"endLine": "endLine",
							"endColumn": "endColumn",
							"security": "level",
							"message": "\\${message} [\\${code}]",
						},
						"securities": {
							"error": "error",
							"warning": "warning",
							"note": "info",
						},
					},
				},
				"formatters": {},
				"filetypes": {
					"shellscript": "shellcheck",
					"lsp-bash": "shellcheck",
					"Bash": "shellcheck",
				},
			},
		},
		"LSP-bash":
		{
			"enabled": false,
			"command": [
				"/opt/homebrew/bin/node",
				"/opt/homebrew/bin/bash-language-server",
				"start"
			],
			"selector": "source.shell",
		},
		"clangd":
		{
			"enabled": true
		},
	},
	"diagnostics_gutter_marker": "circle",
	"log_debug": false,
	"show_symbol_action_links": true,
	"show_diagnostics_count_in_view_status": true,
	"show_diagnostics_in_view_status": true,
	"show_view_status": true,
	// "disabled_capabilities": []
}
```

but with the recent LSP-bash, it's impossible since shellcheck is invoked by LSP-bash… without any options, causing my project to have million warnings…

**Comment by skovhus** [comment]
That does sound annoying.

A temporary workaround is to add file overriding shellcheck configuration: https://github.com/bash-lsp/bash-language-server/issues/464#issuecomment-1221020685

I'm wondering if adding a `.shellcheckrc` to your project root works? Or if we need to add a configuration option to the server.

**Comment by skovhus** [comment]
You can also disable the LSP shellcheck integration for now by setting the `SHELLCHECK_PATH` environment variable to an empty string. Although I would love to find a better solution so you can use the ShellCheck integration from bash-language-server.

**Comment by dmilith** [comment]
Thanks for fast reply :) I managed to figure out that the SHELLCHECK_PATH isn't a path, but a while cmdline… hence I did just:

```sh
"SHELLCHECK_PATH": "/opt/homebrew/bin/shellcheck --exclude=SC2034,SC1090,SC1091,SC2164,SC2181,SC2154,SC2004,SC2016,SC2086,SC2048,SC2148"
```

in my "env" of LSP-bash config :)

**Comment by dmilith** [comment]
Honestly, I'd leave SHELLCHECK_PATH as it is now with auto-detection but would add SHELLCHECK_ARGS maybe? :) Something like that would be great

**Comment by dmilith** [comment]
> You can also disable the LSP shellcheck integration for now by setting the `SHELLCHECK_PATH` environment variable to an empty string.

It is not true though. Since the last two LSP-bash releases it's no longer valid, and an empty string for SHELLCHECK_PATH will autodetect "shellcheck" binary from the $PATH.

**Comment by skovhus** [comment]
> It is not true though. Since the last two LSP-bash releases it's no longer true, and an empty string for SHELLCHECK_PATH will autodetect "shellcheck" binary from the $PATH.

That behavior was removed again in 3.3.0. Can you verify that an empty string disables ShellCheck. At least this works in the vscode client.

**Comment by dmilith** [comment]
I just noticed, that `"SHELLCHECK_PATH": "/opt/homebrew/bin/shellcheck --exclude=SC2034,SC1090,SC1091,SC2164,SC2181,SC2154,SC2004,SC2016,SC2086,SC2048,SC2148"` will fail silently (no linting of fails). So I'm back to my original settings :)

**Comment by skovhus** [comment]
The new environment variable `SHELLCHECK_ARGUMENTS` has now been added and released as `bash-language-server@4.0.0-beta.1`.

NOTE: We already add the following arguments: --shell, --format, --external-sources.

@dmilith can you test out the new version and see if it solves your needs? Note that node >= 14 is now required.

**Comment by skovhus** [comment]
To install the beta release you can run `npm i -g bash-language-server@4.0.0-beta.1`

**Comment by dmilith** [comment]
@skovhus Works like a charm with the new bash-language-server.

**Comment by skovhus** [comment]
@dmilith can you provide the logs from the Bash Language Server? It should log a line "ShellCheck: running" where we can see what arguments it provides.

**Comment by dmilith** [comment]
@skovhus I did some debugging in the meantime and I think it was not working due that I haven't provided the "command" with bash-language-server. I think it's using the default version provided by the extension of my editor instead. To clarify - in Sublime Text, my LSP-bash configuration is as follows:

```json
{
    // @see https://github.com/mads-hartmann/bash-language-server
    "command": ["/opt/homebrew/bin/bash-language-server", "start"],

    "languages": [
        {
            "languageId": "bash",
            "scopes": [
                "source.shell.bash",
            ],
        },
        {
            "languageId": "task",
            "scopes": [
                "source.shell.bash",
            ],
        },
        {
            "languageId": "fun",
            "scopes": [
                "source.shell.bash",
            ],
        },
        {
            "languageId": "fact",
            "scopes": [
                "source.shell.bash",
            ],
        },
    ],
    "initializationOptions": {
    },
    "env": {
        "HIGHLIGHT_PARSING_ERRORS": "0",
        "GLOB_PATTERN": "**/*@(.sh|.fun|.fact|.facts|.task)",
        // "SHELLCHECK_PATH": "",
        "SHELLCHECK_PATH": "/opt/homebrew/bin/shellcheck",
        "SHELLCHECK_ARGUMENTS": "--shell=sh --exclude=SC2034,SC1090,SC1091,SC2164,SC2181,SC2154,SC2004,SC2016,SC2086,SC2048,SC2148",
    },
    "settings": {
        "bash": {
            // ...
        },
    },
}
```

And it seems to work as expected now :) Thanks!

**Comment by skovhus** [comment]
Thanks! 👏 

And feel free to contribute more with ideas on how to improve the extension.
