### ISSUE TITLE
Silently ignore the error when EXPLAINSHELL_ENDPOINT is unavailable

### ISSUE THREAD

**Issue by maximbaz** [bash-lsp/bash-language-server#61]
`EXPLAINSHELL_ENDPOINT` is there to configure the source of the explainshell service, whether it would point to explainshell.com or a local Docker container. I would envision people to configure this environment variable somewhere globally, do it once and forget.

However, there could be times when the explainshell service is not running: Docker container image is stopped, or you have no internet access at the moment.

Currently, when `EXPLAINSHELL_ENDPOINT` is set, but the endpoint is not available, the editor is being spammed with an error:

![image](https://user-images.githubusercontent.com/1177900/42739667-c6e9bb26-889b-11e8-9067-0ce7b0462034.png)

I would like to propose to silently ignore this specific case, when the endpoint is not available, and just continue to try the other existing methods of getting the hover information.

What do you think?

**Comment by mads-hartmann** [comment]
That sounds good to me - we could do a bit of logging just to help people debug a any misconfiguration they might have 👍🏻
