### ISSUE TITLE
 textDocument/typeDefinition are missing ?

### ISSUE THREAD

**Issue by ayoubelmhamdi** [bash-lsp/bash-language-server#637]
# in neovim
I can't use `:lua vim.lsp.buf.type_definition()`
because it gives me this error:
```
method textDocument/typeDefinition is not supported by any of the servers registered for the current buffer
````
But `:lua vim.lsp.buf.definition()` it works fine.

**Comment by skovhus** [comment]
Yeah we don’t provide type definitions. What would you expect those to return?

**Comment by ayoubelmhamdi** [comment]
the `textDocument/typeDefinition` returns one position, but the `textDocument/definition` could return multi-position,

**Comment by skovhus** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition

This is meant for languages with types it seems. Like jump to type definition in rust, TypeScript, etc.
