### ISSUE TITLE
server.js has high CPU usage on MacOS

### ISSUE THREAD

**Issue by BlaineEXE** [bash-lsp/bash-language-server#638]
I'm seeing server.js have very high CPU usage on MacOS. It's reportedly using 2.5 CPU cores on my 6-core i7 processor.

```
❯ ps aux | grep 9478
blaine            9478 276.8 16.8 82455348 2824148   ??  R     9:35AM   4:41.76 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/blaine/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.23.0/out/server.js --node-ipc --clientProcessId=9334
```

**Comment by skovhus** [comment]
Thanks for reporting this. I'm puzzled and would love to figure out what is going on. Can you share some output from the extension (View -> Output -> Bash IDE) while this is ongoing?

**Comment by skovhus** [comment]
Is the high CPU usage only when the extension starts, while typing or also when inactive?

And does it change anything if you open a small workspace with few files compared to opening a large workspace (e.g. home directory)?

**Comment by skovhus** [comment]
@BlaineEXE Do you have shellcheck installed? 

A new version bash-language-server@4.2.4 has just been released, introducing a short execution delay and debouncing for ShellCheck tasks. 

Let me know if the new version works for you.

**Comment by BlaineEXE** [comment]
Just was able to test this, I'm still seeing the issue.

```
blaine           32515 278.1  5.5 82455396 916404   ??  R    11:59AM   1:12.51 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/blaine/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.25.0/out/server.js --node-ipc --clientProcessId=18651
```

**Comment by skovhus** [comment]
Thanks. Not sure if you saw the previous questions, but it would be helpful if you have time to answer them: https://github.com/bash-lsp/bash-language-server/issues/638#issuecomment-1365085765

Do you have shellcheck installed?

**Comment by skovhus** [comment]
I can reproduce high CPU usage if I open a workspace for a sub folder with many files, like my home folder.

**Comment by BlaineEXE** [comment]
> Thanks. Not sure if you saw the previous questions, but it would be helpful if you have time to answer them: [#638 (comment)](https://github.com/bash-lsp/bash-language-server/issues/638#issuecomment-1365085765)
> 
> Do you have shellcheck installed?

Apologies. I was hasty.

I have shellcheck 0.9.0 installed; the latest.

I have 3 projects with many bash scripts in them. If I close all shell script files in all workspaces, I still see the high CPU usage.

**Comment by skovhus** [comment]
We have [fixed a bug causing memory leaks and high CPU usage for workspaces with many files](https://github.com/bash-lsp/bash-language-server/pull/661
) – this has been released as bash-language-server@4.2.5 and the vscode extension 1.26.0. Can you confirm that this solves the issue for now?

**Comment by BlaineEXE** [comment]
Seems to be fixed now. Thanks! 🙏

**Comment by skovhus** [comment]
Thanks for testing this!
