### ISSUE TITLE
Curly brackets and dollar symbol invoke comprehensive completion list

### ISSUE THREAD

**Issue by erusyd** [bash-lsp/bash-language-server#641]
![Peek 2022-12-23 16-46](https://user-images.githubusercontent.com/1529102/209307923-d5ed62c9-b762-4172-9277-e95ecb532233.gif)
![Peek 2022-12-23 17-12](https://user-images.githubusercontent.com/1529102/209307970-f2a27600-9d87-4db4-a68c-2be5158f6160.gif)

I think this pop up is meaningless.

**Comment by skovhus** [comment]
Thanks for reporting this, it seems like a bug.

**Comment by skovhus** [comment]
@erusyd a fix has now been released as bash-language-server@4.5.1 and the latest vscode extension 1.29.0. Let me know if you experience other issues or ideas for future improvements.

**Comment by erusyd** [comment]
I tested it, the dollar($) sign still invokes completion on Emacs.

**Comment by skovhus** [comment]
> I tested it, the dollar($) sign still invokes completion on Emacs.

A dollar sign should always invoke completions as we want to complete on variables — but in some cases we return an empty list back to the client. 

When the dollar sign lonely or part of a word (. e.g. $M) we return a non empty list of completions. In case it is part of a non word like the examples above we return an empty list of completions. 

But please provide an example if something isn’t work as expected.

**Comment by erusyd** [comment]
Solved. It is my Emacs company+yasnippet completion configuration problem.
