### ISSUE TITLE
Spurious error when workspace/configuration receives `[null]` as response

### ISSUE THREAD

**Issue by krobelus** [bash-lsp/bash-language-server#644]
From https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration regarding the `workspace/configuration` response

> The order of the returned configuration settings correspond to the order of the passed ConfigurationItems
> ...
> If the client can’t provide a configuration setting for a given scope then null needs to be present in the returned array.

My client does that - it look like

	From server: {"jsonrpc":"2.0","id":1,"method":"workspace/configuration","params":{"items":[{"section":"bashIde"}]}}
	To server: {"jsonrpc":"2.0","result":[null],"id":1}

bash-language-server response with `window/logMessage` of type warning:

	updateConfiguration: failed with [
	  {
	    "code": "invalid_type",
	    "expected": "object",
	    "received": "null",
	    "path": [],
	    "message": "Expected object, received null"
	  }
	]

I think it should not. I guess I could send `[{}]` but IDK if that's a good idea

Originally reported in https://github.com/kak-lsp/kak-lsp/issues/659

**Comment by skovhus** [comment]
Thanks for reporting this, we should clearly treat `null` differently. 👍

**Comment by skovhus** [comment]
Released as `bash-language-server@4.2.0` and for vscode in the latest extension 1.24.0. Please let me know if this resolves the issue for you.

**Comment by krobelus** [comment]
confirmed fixed, thanks!

**Comment by skovhus** [comment]
@krobelus thanks for checking. Let me know if you have any ideas for improvements. :)
