### ISSUE TITLE
Node error using bash-language-server with Mason

### ISSUE THREAD

**Issue by bellaichef** [bash-lsp/bash-language-server#657]
Hi,

I'm using the following configuration for bash-language-server : 

- Ubuntu 20.04
- NodeJs 14.17.6
- Nvim 0.9

Plugins (in case) : 

-  'wbthomason/packer.nvim'
-  'ellisonleao/gruvbox.nvim'
-  'nvim-tree/nvim-tree.lua'
-  'nvim-tree/nvim-web-devicons'
-  'nvim-lualine/lualine.nvim'
-  'nvim-treesitter/nvim-treesitter'
-  'hrsh7th/nvim-cmp'
-  'hrsh7th/cmp-nvim-lsp'
-  'L3MON4D3/LuaSnip'
-  'williamboman/mason.nvim',
-  'williamboman/mason-lspconfig.nvim',
-  'neovim/nvim-lspconfig',
-  'nvim-telescope/telescope.nvim',

My lua lsp_config  for bash-language-server: 

`require('lspconfig').bashls.setup {
   vim.api.nvim_create_autocmd('FileType', { 
    pattern = 'sh',
    callback = function()
     vim.lsp.start({
        name = 'bash-language-server',
        cmd = { 'bash-language-server', 'start' },
      })
    end,
  }),
    on_attach = on_attach,
    capabilities = capabilities,
  }`
   
(on_attach and capabilities are defined earlier in the config)

I have 2 lsp working without any issue (sumneko lua, phpactor php), but loading bash-language-server crash. 

I have this error in the lsp log : 

`[ERROR][2023-01-05 10:47:19] .../vim/lsp/rpc.lua:734  "rpc" "bash-language-server"  "stderr"  "internal/modules/cjs/loader.js:892
  throw err;
  Error: Cannot find module 'node:child_process'
	Require stack:
	/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/out/server.js
	/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/out/index.js\
	/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/bin/main.js
	    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	    at Module.require (internal/modules/cjs/loader.js:961:19)
	    at require (internal/modules/cjs/helpers.js:92:18)
	    at Object.<anonymous> (/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/out/server.js:12:30)
	    at Module._compile (internal/modules/cjs/loader.js:1072:14)
	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
	    at Module.load (internal/modules/cjs/loader.js:937:32)
	    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
	    at Module.require (internal/modules/cjs/loader.js:961:19) {
		  code: 'MODULE_NOT_FOUND',
		  requireStack: [
		    '/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/out/server.js',
		    '/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/out/index.js',
		    '/home/user/.local/share/nvim/mason/packages/bash-language-server/node_modules/bash-language-server/bin/main.js'
		  ]
	    }"`

opening a .sh with nvim display this message : 

`Client quit with exit code 1 and signal 0`

:LspInfo give this : 

` Language client log: /home/user/.local/state/nvim/lsp.log
 Detected filetype:   sh

 0 client(s) attached to this buffer:

 Other clients that match the filetype: sh

 Config: bashls
  Refer to :h lspconfig-root-detection for help.
  filetypes:         sh
  root directory:    Not found.
  cmd:               bash-language-server start
  cmd is executable: true
  autostart:         true
  custom handlers:

 Configured servers list: bashls, phpactor, sumneko_lua`

I'm a very new user on Mason or lsp and bash-language-server. Anybody would have an idea on how to solve this?

**Comment by bellaichef** [comment]
NodeJS 10.19 was too old. Upgrading to 18.12 solved the issue. Sorry for the disturbing.

**Comment by skovhus** [comment]
No worries. Happy you figured it out, let us know if anything can be clarified in the README or other places.
