### ISSUE TITLE
Options completions/docs: include schemas instead of get-options/explainshell 

### ISSUE THREAD

**Issue by EmilySeville7cfg** [bash-lsp/bash-language-server#668]
Recently I've started project to standardize way to describe tools CLI. Parsing map pages is unreliable in general case and can produce wrong results. I suggest to retrieve auto completions from [this](https://github.com/tldr-pages/tldr-json-schemas) repo and cache them to reuse when no internet connection available. VS Code extension which adds YAML intellisence works in a similar way.

P. S. Of course this project in an early development now, but I hope it will be useful in the future for shells and LSP servers.

**Comment by skovhus** [comment]
Thanks for the suggestion. We currently have two ways of suggesting available options:
- explain shell (but requires a custom server), it does provide excelent results though
- https://github.com/bash-lsp/bash-language-server/blob/main/server/src/get-options.sh which only works if you have installed [bash-completions](https://github.com/scop/bash-completion)

Another project that is more complete but with a similar idea is [fig.io](https://fig.io)'s ("next generation command line") list of documentation for huge list of executable and builtins: https://github.com/withfig/autocomplete/blob/master/src/rm.ts

I'm wondering if you should consider joining forces with them or auto generate tldr-json-schemas from their definitions.

**Comment by EmilySeville7cfg** [comment]
> Another project that is more complete but with a similar idea is [fig.io](https://fig.io/)'s ("next generation command line") list of documentation for huge list of executable and builtins: https://github.com/withfig/autocomplete/blob/master/src/rm.ts

Looks awesome. :) I've never heard about it before.

**Comment by EmilySeville7cfg** [comment]
[Project](https://github.com/tldr-pages/tldr-json-schemas) has been archived, no development happens anymore. This issue can be closed.
