### ISSUE TITLE
shellcheckArguments are set but not used

### ISSUE THREAD

**Issue by lkrms** [bash-lsp/bash-language-server#682]
### Code editor

Visual Studio Code / VSCodium

### Platform

macOS / Linux

### Version

v1.27.0

### What steps will reproduce the bug?

Add to VSCode settings (I've also tried `"-e 1003,1007,..."` and `["-e", "1003,1007,..."]`:

```json
{
"bashIde.shellcheckArguments": "--exclude=1003,1007,1090,1091,2012,2013,2015,2016,2024,2029,2030,2031,2032,2033,2034,2046,2054,2064,2086,2119,2120,2128,2148,2153,2154,2164,2178,2180,2206,2207"
}
```

Move to an editor where one of the checks was being reported as a problem. It will still be reported as a problem, even after:
- Restarting Visual Studio Code
- Deleting and reinstalling all plugins

Meanwhile, the Bash IDE output log contains:

```
ShellCheck: running "shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/lina/Code/lk/****** --source-path=/home/lina/Code/lk/******"
```

And by watching the output of `ps` in another window, I've confirmed no custom arguments are added.

### How often does it reproduce? Is there a required condition?

100% consistent on multiple platforms.

### What is the expected behavior?

Suppression of the numbered `shellcheck` rules when using Bash IDE for linting. (The ability to disable `shellcheck` entirely would be an acceptable alternative, but this doesn't work either -- see Additional Information.)

### What do you see instead?

Disabled `shellcheck` report codes continue to appear in the IDE.

### Additional information

If I use this setting instead, `shellcheck` is supposed to be disabled:

```json
{
   "bashIde.shellcheckPath": ""
}
```

But this setting is also ignored (i.e. `shellcheck` continues to run, and unwelcome errors continue to be reported).

Meanwhile, this appears in Bash IDE's output log repeatedly:

```
[Warn  - 11:21:41 am] updateConfiguration: failed with [
  {
    "code": "unrecognized_keys",
    "keys": [
      "logLevel"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'logLevel'"
  }
]
```

It occurs without `logLevel` being set explicitly and continues when it is set, but setting `logLevel` to `debug` does result in more verbose output.

**Comment by skovhus** [comment]
Thanks for the detailed report! Turns out the vscode extension had the wrong language server version. I'll release a fix soon.

**Comment by skovhus** [comment]
This is now fixed in the latest release (v1.28.0). Let me know if you have other issues or ideas for future improvements. :)

**Comment by lkrms** [comment]
Have just updated and can confirm all of the issues are resolved :)  Thanks so much--very impressive turnaround!

**Comment by skovhus** [comment]
Thanks for testing this out!
