### ISSUE TITLE
Ignore zsh files in shellcheck

### ISSUE THREAD

**Issue by remcohaszing** [bash-lsp/bash-language-server#689]
### Code editor

Visual Studio Code

### Platform

Linux

### Version

v1.29.0

### What steps will reproduce the bug?

Open `.zshrc` or a file with the `.zsh` extension

### How often does it reproduce? Is there a required condition?

The language is configured as _Shell Script (shellscript)_. This is default behaviour in VSCode.

### What is the expected behavior?

Nothing

### What do you see instead?

It’s checked by Shellcheck, which can’t handle ZSH syntax. This results in a lot of errors.

### Additional information

The solution would be to ignore validation of `.zshrc` and `*.zsh` files.

**Comment by skovhus** [comment]
That is a really good point. We could also use the shebang, which we are currently parsing. 

Note that the treesitter parser we are using isn't really supporting zsh either. #252 

Let me know if you want to help out fixing this issue.

**Comment by skovhus** [comment]
Thanks for the detailed report! That does make a lot of sense. A fix should be out within the next hour. 

Let us know if you have other suggestions.

**Comment by remcohaszing** [comment]
Thank you!

**Comment by lodagro** [comment]
Using vscode 1.75.0 on linux with Bash IDE 1.35.0, this problem can be reproduced.

foo.zsh
```sh
#!/usr/bin/env zsh
source somestuff
```

This triggers the bash-language-server into showing a problem on the ```source``` statement.

```
Source command could not be analyzed: failed to resolve path.

Consider adding a ShellCheck directive above this line to fix or ignore this:
# shellcheck source=/my-file.sh # specify the file to source
# shellcheck source-path=my_script_folder # specify the folder to search in
# shellcheck source=/dev/null # to ignore the error bash-language-server
```

The Bash IDE glob pattern i have is the default one:
```
**/*@(.sh|.inc|.bash|.command)
```

**Comment by skovhus** [comment]
The error here has nothing to do with shellcheck, but is caused by us not being able to follow the source command. But we do use the shellcheck directive to guide us understanding the source command. 

I understand that this can be confusing. Any idea on how to improve this? If we remove the diagnostic/error, then the user might not understand why jump to definition, documentation etc doesn’t work across the sourced file.

**Comment by lodagro** [comment]
If this message would show up in a bash script, that would be fine (although i thought that shellcheck did run).

It is my understanding zsh scripts are not supported by the Bash IDE, so i do not expect it to run at all. I took the source only as an example to show the Bash IDE is running on a script where i do not expect the Bash IDE to run on.

**Comment by skovhus** [comment]
> It is my understanding zsh scripts are not supported by the Bash IDE

well the support is not great, but it does a decent job for a lot of simpler zsh scripts. But we could disable this specific error for zsh files. Note that the language server is called for any 🐚-scripts and we just try to be helpful in return. 

Official zsh support
