### ISSUE TITLE
`includeAllWorkspaceSymbols` does not respect ShellCheck

### ISSUE THREAD

**Issue by babaric-dev** [bash-lsp/bash-language-server#712]
### Code editor

Visual Studio Code

### Platform

Unix

### Version

v1.33.0

### What steps will reproduce the bug?

```bash
#!/bin/bash
source <(somecommand)
```

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

Without ShellCheck directive (`# shellcheck source=/dev/null`): only either warning / info appears
With directive: the LSP should respect ShellCheck's directive so no error message should appear.

### What do you see instead?

Considering the code snippet above, there are actually 2 problems.
- Without directive: SC1090 error and non-constant source error from bash-language-server (duplicated errors?)
- With directive: the error from ShellCheck disappears but the one from bash-language-server doesn't

**Comment by skovhus** [comment]
Thanks for creating this. So this isn't really related to the `includeAllWorkspaceSymbols` feature right? But this is a feature request to pass ShellCheck directives for source statements (which makes a lot of sense).

**Comment by babaric-dev** [comment]
Yes.
It just doesn't respect shellcheck's `source=/dev/null` and its pretty annoying i cant hide the error.

**Comment by Backtix** [comment]
+
Yupp, it's so annoying I have to disable my LSP tab

**Comment by skovhus** [comment]
> Yupp, it's so annoying I have to disable my LSP tab. 

Just to understand: the diagnostic is so annoying that you would rather not use the extension and not have any auto completion, jump to definition, documentation etc? If that is true for more users, then we should be careful about using any diagnostics and make them possible to disable. 

In the mean time you could just disable shellcheck by adding an empty string for the `bashIde.shellcheckPath` config option: https://github.com/bash-lsp/bash-language-server/blob/main/vscode-client/package.json#L66

**Comment by Backtix** [comment]
> > Yupp, it's so annoying I have to disable my LSP tab.
> 
> Just to understand: the diagnostic is so annoying that you would rather not use the extension (...)

No, I still use the extension but have hide the tab in my editor (Kate) since I get distracted all the time. But if there is a 'real' error in my script, it's harder to see.

But I have to admit, that I thought about completely disabling the LSP since it's so distracting getting errors highlighted all the time.

**Comment by skovhus** [comment]
Thanks for the additional context. Does your editor differentiate between different diagnostics severities? They are not all errors.

**Comment by Backtix** [comment]
![LSP_arr](https://user-images.githubusercontent.com/66909130/217173512-c4b9d53c-0e39-45c4-b991-9e2bb76ad955.png)
![LSP_arr_trun](https://user-images.githubusercontent.com/66909130/217173509-b334c234-7308-4197-8814-dc384b077035.png)

Yes, it does. The problem is that it pushes the more important diagnostics down.
Even if I configure it not to automatically expand the tree structure, it's annoying.
Only an empty diagnostics tab is a good diagnostics tab :)

**Comment by Backtix** [comment]
Needed to hard-code the sourcing paths now, since this issue got so annoying with multiple sourced files. Hope this will get fixed soon. Especially because "Kate" seem to expand all the [bash-language-server] with every new warning/error.

**Comment by babaric-dev** [comment]
Any updates on this?

**Comment by skovhus** [comment]
There hasn't been any work on this issue, but contributions are more than welcome.

Related https://github.com/bash-lsp/bash-language-server/issues/738

**Comment by skovhus** [comment]
The warning was added to inform the user why features like jump to definition and documentation across files aren’t working. But I’m considering if we should just disable them — do we see that they provide enough value (even if we parse shellcheck directives)?

**Comment by skovhus** [comment]
We are now parsing shellcheck directives in version 1.34 of the vscode extension and the server version 4.8.1.

Let me know if this works for you, and if you have further ideas for improving this (or the extension/server in general). Thanks!
