### ISSUE TITLE
Autocomplete for options not working

### ISSUE THREAD

**Issue by babaric-dev** [bash-lsp/bash-language-server#718]
### Code editor

Visual Studio Code

### Platform

Unix

### Version

v1.33.0

### What steps will reproduce the bug?

```
#!/bin/bash
ls -
```

### How often does it reproduce? Is there a required condition?

On my machine, I am able to reproduce it every single time.

### What is the expected behavior?

The options like `--sort` or `-l` should appear.

### What do you see instead?

Nothing shows up.

### Additional information

After a bit of debugging, it seems like `getCommandOptions` in `server.ts` is never called.

Log when typing `-` in `ls -`:
```
14:46:42.676 DEBUG onCodeAction: found 0 code action(s)
14:46:42.757 DEBUG onDocumentSymbol
```

Also, the `get-options.sh` worked from the command line by directly running it and supplying arguments (e.g `.../get-options.sh "ls" "-"`). So I don't think the problem is there.

**Comment by foodornt** [comment]
is it supposed to work anyways?

**Comment by babaric-dev** [comment]
Sorry. But are there any updates?

**Comment by skovhus** [comment]
Autocompletions for command options are not triggered automatically, you need to use the autocompletion key (usually Ctrl+Space in vscode).
