### ISSUE TITLE
bashls triggers a registerCapability handler despite dynamicRegistration set to false

### ISSUE THREAD

**Issue by WhyNotHugo** [bash-lsp/bash-language-server#722]
### Code editor

neovim

### Platform

Linux

### Version

4.6.2

### What steps will reproduce the bug?

Just run neovim with the LSP configured.

### How often does it reproduce? Is there a required condition?

Always, at startup.

### What do you see instead?

Neovim's logs state:

```
[WARN][2023-02-08 18:16:51] ...lsp/handlers.lua:113	"The language server bashls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

### Additional information

Nothing special about my setup. I don't see any obvious issues.

**Comment by skovhus** [comment]
Thanks for reporting this. Wondering why we never saw this issue before, maybe users are on an old version?

**Comment by WhyNotHugo** [comment]
It doesn’t seem to have any obvious impact. Any idea what kind of capability is registered that the editor could miss?

**Comment by David-Else** [comment]
I have noticed that in Helix I am able to use the rename code action, and only when I press enter it tells me 'language server does not support symbol renaming'. Could this be related, I think other servers warn in advance, but I might be misremembering.

**Comment by skovhus** [comment]
Closed by https://github.com/bash-lsp/bash-language-server/pull/763

let me know if the new version works for you.

**Comment by David-Else** [comment]
> I have noticed that in Helix I am able to use the rename code action, and only when I press enter it tells me 'language server does not support symbol renaming'. Could this be related, I think other servers warn in advance, but I might be misremembering.

This still happens with 4.8.3, should it report it does not support renaming before prompting to enter the new name?

**Comment by skovhus** [comment]
So the server does not support renaming, so I’m curious why helix believes this. Is this the same for other languages and clients?

**Comment by David-Else** [comment]
I don't know any other servers that don't support renaming, so I am not sure how to test. Maybe @the-mikedavis can shed some light on it.

**Comment by the-mikedavis** [comment]
That's an issue on our end - we check the server capabilities after entering the replacement in the prompt. I opened up https://github.com/helix-editor/helix/issues/6249 to improve that UX
