### ISSUE TITLE
Backticks cause strikethrouigh in VS Code

### ISSUE THREAD

**Issue by dseynhae** [bash-lsp/bash-language-server#735]
### Code editor

Visual Studio Code

### Platform

WSL (Linux Ubuntu)

### Version

v1.33.0

### What steps will reproduce the bug?

Consider this small test:

```bash
#!/bin/bash

TEST=`which "$0"``
printf "%s\n", "$TEST"
```

Anywhere where backticks are used, the text gets rendered with strikethrough:

![image](https://user-images.githubusercontent.com/54114043/220223985-0f27307a-cb84-45b4-85d4-778c70df5692.png)

I know that `$(...)` is preferred, but I have to review scripts I haven't written...

### How often does it reproduce? Is there a required condition?

This happens anywhere where backticks are used for command substitution.

### What is the expected behavior?

The text should not be rendered with strikethrough...

### What do you see instead?

No strikethrough, I want to be able to read the text.

**Comment by skovhus** [comment]
It seems you have installed ShellCheck, which gives the following diagnostic/problem:
```
Use $(...) notation instead of legacy backticks `...`.shellcheck[SC2006](https://www.shellcheck.net/wiki/SC2006)
```

Can you confirm that this is the case? If so, then this is expected behaviour. Note that there are several ways of ignoring error from shellcheck: https://www.shellcheck.net/wiki/Ignore
