### ISSUE TITLE
BashIDE reports SC1091 issues even with "bashIde.shellcheckPath" empty

### ISSUE THREAD

**Issue by glhez** [bash-lsp/bash-language-server#790]
### Code editor

Visual Studio Code

### Platform

Windows

### Version

4.8.2

### What steps will reproduce the bug?

My directory contains several files and is split like this:

```
C:/
└── foo/
    ├── foobar/
    │   └── lib/
    │       └── utils.bash
    └── foobar-user/
        ├── bin/
        │   └── someexecutable
        └── foobar.code-workspace
```

Whenever I edit `someexecutable`, or rather after some time, I get some shellcheck SC1091 errors: https://www.shellcheck.net/wiki/SC1091

The shellcheck directive is used as follow

```bash
# shellcheck source=../foobar/lib/utils.bash
source "${FOOBAR_HOME}/lib/utils.bash"
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

No issues because I have made "bashIde.shellcheckPath" empty in VSCode settings.

### What do you see instead?

The error I got are:

> Source command could not be analyzed: failed to resolve path.
> 
> Consider adding a ShellCheck directive above this line to fix or ignore this:
> - shellcheck source=/my-file.sh # specify the file to source
> - shellcheck source-path=my_script_folder # specify the folder to search in
> - shellcheck source=/dev/null # to ignore the error

### Additional information

I am also using [ShellCheck](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck).

I am getting double the error because the two extension overlaps, but some key part of their configuration differs: ShellCheck allows setting the directory where the workspace is as "current working directory":

```
[2023-03-23T17:42:38.000Z] [DEBUG] Spawn: (cwd=C:\foo\foobar-user) [...]\.vscode\extensions\timonwong.shellcheck-0.29.4-win32-x64\binaries\win32\x64\shellcheck.exe [ '-f', 'json1', '--external-sources', '-' ]
```
Thus, shellcheck evaluate the source=... like this: `C:\foo\foobar-user/../foobar/lib/utils.bash`

I don't know what BashIDE does (I was redirected here from https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode "Repository") but even with the shellcheck empty, I still get the warnings.

**Comment by skovhus** [comment]
Thank you so much for reaching out!

Note that the warning “Source command could not be analyzed” isn’t related to ShellCheck, it informs the user that jump to definition and documentation across files wouldn’t work as we failed to analyse the source command. But we do use ShellCheck directives to help you fix the issue.

But this message seems confusing to multiple people, so I've made it configurable and disabled by default. See https://github.com/bash-lsp/bash-language-server/pull/794 – this was released as vscode extension 1.36 and bash-language-server version 4.8.4.

Please let us know if you have other problems or suggestions for new features.
