### ISSUE TITLE
Shellcheck use all CPU and RAM on my computer

### ISSUE THREAD

**Issue by romaincabassot** [bash-lsp/bash-language-server#804]
### Code editor

VS Code

### Platform

Ubuntu 22.04

### Version

1.36.0

### What steps will reproduce the bug?

Since 1.36.0 Bash IDE vscode extension launches shellcheck process that consume 99% cpu each and memory consumption grows until all my 32GB RAM are used causing system to be unresponsive.
Disabling extension or rollbacking to 1.35.0 solve the issue (even with shellcheck extension enabled).

I've a VSCode workspace with 78293 files (593 shell scripts). This workspace is Git repository with many Git submodules.

Process launched looks like that:
`myuser  173469  173252 98 10:30 ?        00:00:55 shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/myuser/workspace/myproject --source-path=/home/myuser/workspace/myproject/binary-files/scripts/lib -`

I don't know why there two external sources and the second is a subfolder of the first. Maybe this is normal?

### How often does it reproduce? Is there a required condition?

Everytime in my workspace

### What is the expected behavior?

Don't use so much resources

### What do you see instead?

Unresponsive computer/programs crashing

### Additional information

Ask me for more information if needed.

Thank you

**Comment by garlik6** [comment]
Same issue

**Comment by romaincabassot** [comment]
Regarding my initial issue I think that the problem does not comes from bash-lsp but rather from shellcheck.
And I've been working on a script on which two bash files source each other => I think that's the real issue and, even the bash script works fine, this is something that may have to be handled in the script so I close the ticket.

**Comment by annahri** [comment]
Hi @romaincabassot do you have the resolution for this? 

I encountered the same. Every time I open a shell script, shellcheck runs in the backround. But when I quit, it stays. If I open it again, it spawns another instance until it eat up all my RAM and freezes my laptop.

**Comment by jobeirne-nydig** [comment]
Script that watches for rogue shellcheck processes and kills them:
```sh
#!/bin/bash

# Define memory limit in kilobytes (5 GiB = 5 * 1024 * 1024 KB)
MEMORY_LIMIT=$((5 * 1024 * 1024))

echo "Defending your system against rogue shellchecks..."

while true; do
    ps -eo comm,pid,rss | while read -r COMM PID RSS; do
      if [[ "$COMM" == "shellcheck" && "$RSS" -gt "$MEMORY_LIMIT" ]]; then
        echo "Process $COMM (PID: $PID) is using $RSS KB of memory, exceeding limit. Killing it."
        
        kill -9 "$PID"
      fi
    done

    sleep 5
done
```
