### ISSUE TITLE
Please make "mute" the default setting for tooling output/logging

### ISSUE THREAD

**Issue by aplatypus** [bash-lsp/bash-language-server#88]
I plugged in the docker "explain shell" container today and almost every time I move the cursor or type something the terminal window re-opens and prints out loads of text I don't need to see.

Or better yet, I "could see it if I choose" and otherwise I expect that kind of noise to sit in the background.  It almost makes the Bash-IDE unsuable.

**Comment by skovhus** [comment]
@aplatypus thanks for reporting this – and sorry for the late reply.

Can you share a screenshot? I'm not exactly sure what the issue is.

**Comment by skovhus** [comment]
I cannot reproduce. Please reopen with a screen shot.
