### ISSUE TITLE
Failed to parse expression on bitwise operations

### ISSUE THREAD

**Issue by nanortemis** [bash-lsp/bash-language-server#89]
I'm getting an error when i have statements like this one:
`echo "$((1 << 5))"`

Version: 1.5.4

**Comment by skovhus** [comment]
Thanks! This is an error in the underlying parser. 

Can you create a ticket here: https://github.com/tree-sitter/tree-sitter-bash ?

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
