### ISSUE TITLE
Does the VSCode extension provide function folding support?

### ISSUE THREAD

**Issue by james-klein-sfcc** [bash-lsp/bash-language-server#920]
I've been looking for a way to collapse Bash functions like you can do OOTB with e.g. JavaScript. I don't see that in the features list and though I did test it (unsuccessfully) I want to make sure I'm not just doing something wrong. In my mind it's a major feature so I'm not sure why I'm struggling to get support for it.

**Comment by skovhus** [comment]
Thanks. We currently do not support this, but contributions are more than welcome.

Related to https://github.com/bash-lsp/bash-language-server/issues/18
