### ISSUE TITLE
tree-sitter-bash has updated to 0.20.0 w/ many bug fixes

### ISSUE THREAD

**Issue by amaanq** [bash-lsp/bash-language-server#943]
Hey, I've seen in some issues bash-ls uses tree-sitter-bash under the hood for parsing.

I've recently fixed many (20+?) issues upstream in tree-sitter-bash, and parsing works much better for many cases 

I'm just dropping this by so you guys can update and try it out, and hopefully improve the ls :)

**Comment by skovhus** [comment]
Thanks. Yeah we have actually been using a custom build of tree sitter for some time based on their main branch. 

But I’m happy if we can get rid of those GitHub actions and start relying on packages being published again. 🤞
