### ISSUE TITLE
Don't enable shellcheck linting by default

### ISSUE THREAD

**Issue by Zeioth** [bash-lsp/bash-language-server#999]
### What is the problem this feature will solve?

On neovim, when installing `bash-language-server` along with `shellcheck`, this triggers linting two times.

### What is the feature you are proposing to solve the problem?

Make shellcheck linting disabled by default, and opt-in. As linting is the responsability of a linter, not the responsability of a lsp server.

### Screenshot

![screenshot_2023-10-15_16-56-14_110873179](https://github.com/bash-lsp/bash-language-server/assets/3357792/330b78f5-d9fd-409c-8df7-60c362d9030a)

**Comment by Zeioth** [comment]
The right way to set it up is to add this options to null-ls
```lua
opts = function()
  local nls = require "null-ls"
  return {
    sources = {
      -- Shellcheck - Enable only code actions (linting goes trough bashls)
      nls.builtins.code_actions.shellcheck,
    },
  }
end
```

* This way null-ls will only use code actions for shellsheck, and it won't enable linting, since bashls is gonna enable it anyway.
* With this we achieve having access to bahsls code actions AND null-ls code actions.

**Comment by Zeioth** [comment]
Ok after further research I managed to disable it with
```
local lsp_opts = utils.extend_tbl(server, { capabilities = M.capabilities, flags = M.flags })
if server_name == "bashls" then -- by default disable shellcheck
  lsp_opts.settings = { bashIde = { shellcheckPath = "" } }
end
```

And while that keep the lsp capabilities, it disables the bash-language-server code actions for code fixes, which I find super valuable. So I'm closing this.

**Comment by Zeioth** [comment]
In case someone is interested, this is how I made compatilbe `bash-language-server` and `shellcheck` on my neovim config:

## null-ls
```lua
  --  null-ls [lsp code formatting]
  --  https://github.com/nvimtools/none-ls.nvim
  {
    "nvimtools/none-ls.nvim",
    dependencies = {
      {
        "jay-babu/mason-null-ls.nvim",
        cmd = { "NullLsInstall", "NullLsUninstall" },
        opts = { handlers = {} },
      },
    },
    event = "BufEnter",
    opts = function()
      local nls = require "null-ls"

      -- Disable servers manually here
      require("null-ls").disable("shellcheck")

      return {
        sources = {
          -- You can customize your formatters here.
          nls.builtins.formatting.beautysh.with {
            command = "beautysh",
            args = { "--indent-size=2", "$FILENAME" },
          },
          -- Shellcheck - Enable only code actions (for linting we use bashls)
          nls.builtins.code_actions.shellcheck,
        },
        on_attach = require("base.utils.lsp").on_attach,
      }
    end,
  },
```

## LSP config
```lua
if server_name == "bashls" then -- by defauls use mason shellcheck path
  lsp_opts.settings = { bashIde = { shellcheckPath = vim.fn.stdpath "data" .. "/mason/bin/shellcheck" } }
end
```

This way `bash-language-server` has all its normal capabilities and aditionally:

* Mason install shellcheck for us. (to eliminate external dependencies)
* Null ls disable diagnostics, but enable code actions. (to prevent double diagnostics + adding code actions for silencing rules)

**Comment by Zeioth** [comment]
## Easier way to reproduce
* Having at least one external source installed (any null-ls package that is not builtin)
* `:LspStop` and then `:LspStart`

Maybe null-ls times out? When I do `:LspRestart`, I don't experience this bug.

**Comment by adoyle-h** [comment]
@Zeioth `nls.builtins.code_actions.shellcheck` shellcheck is not found in none-ls
